<script>
	export let name;
    export let score;
    export let boxOffice;
    export let sort
    export let release
    export let phase

    let options = { year: 'numeric', month: 'long'  };
    let date  = new Date(release);

</script>

<div class="section { (sort > 11 ? parseInt(sort)+2 : sort>7 ? (parseInt(sort)+1) : sort)%2 ==1 ? 'grey'  : '' } wf-section">
  <div class="div-block-7 {sort==7 || sort == 11 ? "bottom" : sort==8 || sort == 12 ? "top" : ""}">
    <div class="explanation">
      {#if sort != 8 && sort != 12}
      <h3 class="heading-4">{name}</h3>
      <h1 class="heading-5">{date.toLocaleDateString("en-US", 
// @ts-ignore
      options)}</h1>
        <div class="text-block">Score: <strong>{score}%</strong> <em>(Rotten Tomatoes)</em></div>
        <div class="text-block">Box Office: <strong>{Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0},).format(boxOffice)}</strong></div>
      {/if}
      <div class="div-block-9">
        {#if phase==1}
          {#if sort == 1}
            <p class="paragraph">Everything started in <strong>2008</strong> with <strong>Iron Man</strong>. It is the <strong>first</strong> movie of the Marvel Cinematic Universe and a <strong>gamble</strong>; if it flopped, everything might have stopped here.<br><br>In the movie, <strong>Tony Stark</strong> <em>(perfectly interpreted by Robert Downey</em> <em>Jr)</em> is an eccentric <strong>billionaire</strong> who made his fortune by building and selling <strong>weapons.<br> <br></strong>After being <strong>kidnapped</strong> by a terrorist organization, he escapes using an <strong>iron suit</strong> he created while pretending to obey the terrorists' orders. Back home, Tony <strong>perfects</strong> his suit and announces that his company will <strong>stop</strong> manufacturing weapons. <br><br> Tony discovers that his friend, <strong>Obadiah Stane</strong> <em>(Jeff Bridges)</em>, planned his kidnapping to get control over <strong>Stark Industries</strong> and stops him.<br><br>At the movie&#x27;s end, Tony Stark reveals his identity: &quot;<strong>I am Iron Man</strong>&quot;. <br><br>In the post-credit scene, Nick Furry <em>(</em><em>Samuel L. Jackson</em>) invites Tony Stark to join the <strong>Avengers</strong> initiative.<em></em></p>
            {:else if sort == 2}
            <p class="paragraph">The <strong>second</strong> movie of the MCU. It is also the <strong>worst-rated</strong> one of Phase One and the lowest of all MCU movies at the box office. In this movie <em>(and this one only)</em>, <strong>Bruce Banner </strong>is played by <em>Edward Norton</em>.<br><br>In the movie, Banner transforms into the <strong>Hulk</strong> after exposure to <strong>gamma radiation</strong>.<br><strong><br>General Thaddeus Ross</strong>, who worked with <strong>Bruce</strong>, wants to capture and <strong>weaponize</strong> the Hulk. He tracks Bruce and sends special forces, led by <strong>Emil Blonsky</strong>, to capture him. <br><br>Blonsky is injected with Banner&#x27;s blood and mutates into the <strong>Abomination</strong>. The Hulk defeats the Abomination but spares his life. <br><br>Later, <strong>Tony Stark</strong> approaches <strong>Ross</strong> at a local bar and informs him that a <strong>team</strong> is being put together. The MCU is started. <br></p>
            {:else if sort == 3}
            <p class="paragraph">The <strong>third</strong> movie of the MCU and a direct <strong>sequel</strong> to the first Iron Man also includes <strong>Natasha Romanoff </strong><em>(Scarlett Johansson)</em>, aka <strong>Black Widow&#x27;s </strong>debut.<br><br>In the movie, Stark learns that the <strong>palladium</strong> that keeps him alive and powers the suit is <strong>poisoning</strong> and slowly <strong>killing</strong> him.<br><br>At the Monaco Grand Prix, Stark is attacked by <strong>Ivan Vanko</strong> <em>(Mickey Rourke)</em>, who wants to prove to the world that Iron Man was not invincible and get revenge for his father. At Tony's birthday party, <strong>James Rhodes</strong> confiscates a new prototype suit because of Tony's behavior.<br><br>Later, Tony discovers a hidden message from his <strong>dad</strong> and manages to synthesize a new <strong>element</strong> to replace the palladium, saving his life. In the end, Stark and Rhodes reunite and defeat <strong>Vanko</strong> and an army of drones he built for Justin Hammer. <br><br>In a post-credits scene, agent <strong>Phil Coulson</strong> reports the discovery of a <strong>large hammer</strong> in the desert of New Mexico.<br><br><em>Note: Terrence Howard was replaced by Don Cheadle to play James Rhodes</em><strong><em>.</em></strong><em> </em></p>
            {:else if sort == 4}
            <p class="paragraph">The <strong>fourth</strong> movie of the MCU introduced many important characters like <strong>Thor</strong> himself<em> (</em><em>Chris Hemsworth)</em>, <strong>Loki</strong> <em>(Tom Hiddleston)</em>, and <strong>Clint Barton</strong> <em>(Jeremy Renner),</em> aka <strong>Hawkeye</strong>.<br><br>The movie starts in <strong>Asgard</strong>, when <strong>Odin&#x27;s</strong> son, <strong>Thor</strong>, prepares to become <strong>king</strong>. After a fight, Odin punishes his son for his arrogance by removing his power and exiling him to Earth. Thor&#x27;s hammer, <strong>Mjölnir</strong>, can now only be lifted by someone <strong>worthy</strong>.<br><br>Thor lands in New Mexico and receives help from <strong>Dr. Jane Foster</strong> and <strong>Dr. Selvig</strong>. He finds Mjölnir but is unable to lift it. <br><br>Thor&#x27;s brother, <strong>Loki</strong>, was plotting against him to take the throne of Asgard. He sends the Destroyer on Earth to kill Thor. Thor becomes worthy of Mjölnir again and leaves Earth. He confronts Loki, who falls into the abyss.<br><br>Ultimately, <strong>Selvig</strong> meets <strong>Nick Fury</strong>, who asks him to study the <strong>Tesseract</strong><strong>.</strong><br></p>
            {:else if sort == 5}
            <p class="paragraph">The <strong>fifth</strong> movie is <strong>first </strong>in <strong>chronological</strong> order. <br><br><strong>Steve Rogers</strong> <em>(Chris Evans)</em> enlists in a <strong>super-soldier</strong> experiment program giving him <strong>extraordinary strength</strong>. He meets agent <strong>Peggy Carter</strong> <em>(Hayley Atwell)</em> and <strong>Howard Stark</strong> <em>(Dominic Cooper)</em>, who gives him a <strong>shield</strong> made of <strong>vibranium</strong>. Steve Rogers becomes <strong>Captain America</strong>.<br><br>During a mission, Steve&#x27;s best friend, <strong>James "Bucky" Barnes</strong> <em>(Sebastian Stan)</em>, falls from a train to his apparent death. Steve discovers the location of the last Hydra base and plans to stop Hydra's head, <strong>Johann Schmidt</strong> <em>(Hugo Weaving)</em>, from launching bombs on American cities. <br><br> During the final fight, Schmidt handles the <strong>Tesseract</strong> that he stoled and <strong>disappears</strong> into space. The Tesseract and Rogers end up <strong>crashing</strong> into the <strong>Arctic ocean</strong>. <br><br>Rogers awakens, and <strong>Nick Fury</strong> informs him that he has been asleep for nearly <strong>70 years</strong> and has a new <strong>mission</strong> for him.<br></p>
            {:else if sort == 6}
            <p class="paragraph">The <strong>last</strong> movie brings all heroes <span class="text-span-2"><sub class="subscript">○</sub></span> <strong>together</strong>! <br><br><strong>Loki</strong> promises to the chief of the <strong>Chitauri</strong> to retrieve the <strong>Tesseract</strong> in exchange for an army able to conquer Earth. He steals the Tesseract from <strong>Selvig</strong> and <strong>Fury</strong>.<br><br>The heroes confront Loki in Germany. He ends up imprisoned but escapes and <strong>kills </strong><span class="text-span"><strong class="bold-text-2">Coulson</strong></span><strong>.</strong> His death <strong>motivates</strong> the <strong>Avengers</strong> to work together.<br><br>Loki opens a <strong>wormhole</strong> for the Chitauri to invade Earth. Together, <strong>the Avengers</strong> defend <strong>New York City</strong> and the <strong>Hulk</strong> <em>(this time interpreted by Mark Ruffalo)</em> beats <strong>Loki</strong>. <br><br>In the end, Stark manages to destroy the Chitauri forces by diverting a <strong>nuclear weapon</strong> through the wormhole.<br><br>After the credit, <strong>Thanos</strong> is informed of the failure of the plan. Phase One ends with the heroes eating some well-deserved <strong>Shawarma</strong>.<br></p>
          {/if}
          
        {:else if phase==2}
          {#if sort == 1}
            <p class="paragraph"><strong>Phase Two</strong> also starts with an <strong>Iron Man</strong> movie.<strong><em><br><br></em></strong>Following the event of <strong>The Avengers, Tony Stark</strong> <em>(Robert Downey Jr.) </em>suffers from <strong>post-traumatic stress disorder</strong> while <strong>terrorist attacks</strong> are occurring in the country.<br><br>When <strong>Happy</strong> <em>(Jon Favreau) </em>gets hurt in one of the attacks, Stark decides to <strong>confront</strong> the <strong>Mandarin</strong>, resulting in his house and armors being <strong>destroyed </strong>and him ending up in a small town after being nearly <strong>killed</strong><strong>.</strong><br><br>With the help of a local kid, <strong>Harley Keener </strong><em>(Ty Simpkins)</em>, Tony discovers that the bombings result from people rejecting a regenerative treatment, <strong>Extremis</strong> and that the <strong>Mandarin</strong> was nothing but a <strong>cover-up.</strong><br><br>With the help of <strong>Pepper Potts</strong> <em>(Gwyneth Paltrow)</em> and <strong>Rhodes </strong><em>(</em><em>Don Cheadle),</em> Stark manages to fight and win against the real threat, <strong>Aldrich Kilian </strong><em>(Guy Pearce).<br></em><br>In the end, Stark gets <strong>surgery,</strong> making him less dependent on his technology, and promises Pepper to scale down as <strong>Iron Man</strong>. </p>
            {:else if sort == 2}
            <p class="paragraph">The <strong>second</strong> and <strong>lowest ranked</strong> movie of <strong>Phase Two</strong> follows <strong>Thor</strong> <em>(Chris Hemsworth)</em>, <strong>Loki</strong> <em>(Tom Hiddleston)</em>, and <strong>Jane Foster</strong> <em>(Natalie Portman)</em><strong> </strong>in their new adventure.<br><br>The <strong>Convergence</strong> creates <strong>portals</strong> between the different <strong>worlds</strong>. <strong>Jane Foster</strong> is <strong>teleported</strong> to a world where she absorbs the <strong>Aether</strong>, awakening the dark elf, <strong>Malekith</strong>.<br><br>Malekith attacks <strong>Asgard</strong>, and Thor seeks the <strong>help</strong> of his brother, <strong>Loki</strong>, who is imprisoned. <br>They <strong>fight</strong> Malekith on <strong>Svartalfheim</strong> but <strong>fail</strong>: Malekith <strong>merges</strong> with the <strong>Aether</strong>, and <strong>Loki</strong> is <strong>stabbed</strong> to his <em>(again)</em> apparent <strong>death</strong>. <br><br><strong>Thor</strong> fights <strong>Malekith</strong> in <strong>London</strong> and <strong>defeats</strong> him with the help of <strong>Jane</strong> and <strong>Erik Selvig</strong>. He returns to Asgard, and we learn that <strong>Loki</strong> is <strong>alive</strong> and impersonating Odin. <br><br>The Aether, containing the <strong>Reality Stone</strong>, is taken to <strong>Taneleer Tivar, </strong>aka the <strong>Collector</strong>, who reveals his desire to <strong>acquire</strong> the five other <strong>infinity stones</strong>. <br></p>
            {:else if sort == 3}
            <p class="paragraph">The <strong>third</strong> movie of Phase Two sees the return of <strong>Steve Rogers </strong><em>(Chris Evans)</em>, <strong>Natasha Romanoff </strong><em>(Scarlett Johansson)</em>, and <strong>Bucky Barnes</strong> <em>(Sebastian Stan)</em>. It also introduces a new hero, <strong>Sam Wilson</strong> <em>(Anthony Mackie)</em>.<br><br><strong>Captain America</strong> is working for the <strong>S.H.I.E.L.D </strong>and learns from <strong>Fury</strong> about <strong>Project Insight</strong>, a way to <strong>preemptively</strong> eliminate <strong>threats</strong>. Fury is <strong>attacked</strong> by the <strong>Winter Soldier</strong> and warns Steve that S.H.I.E.L.D is <strong>compromised</strong>.<br><br><strong>Steve</strong> and <strong>Natasha</strong> recruit <strong>Sam</strong>, aka <strong>Falcon</strong>, and they discover that Project Insight&#x27;s goal was to eliminate threats to <strong>Hydra</strong>, who was <strong>secretly</strong> reforming under <strong>Arnim Zola</strong>&#x27;s<strong> </strong>plan<strong>.</strong><br><br>Steve discovers that the <strong>Winter Solider</strong> is his friend, <strong>Bucky</strong>, who was brainwashed. <br><br>In the end, Steve manages to <strong>stop</strong> Project Insight. He and Sam are planning to <strong>find Bucky</strong>. In the post-credit, we see <strong>Hydra</strong> with Loki&#x27;s <strong>scepter</strong> and two enhanced subjects. <br></p>
            {:else if sort == 4}
            <p class="paragraph">The <strong>fourth</strong> movie is the most critically acclaimed of Phase Two. It is taking us to space, far from the event on Earth, and introduces the <strong>Guardians of the Galaxy</strong> and another Infinity Stone: the <strong>Power Stone</strong>.<br><br><strong>Peter Quill</strong> <em>(Chris Pratt) </em>finds a mysterious <strong>artifact</strong>, the <strong>Orb</strong>. <strong>Ronan</strong>, under the command of <strong>Thanos</strong>, sends <strong>Gamora</strong> <em>(Zoe Saldaña) </em>to retrieve the artefact.<br><br>After a fight, <strong>Quill</strong> and <strong>Gamora</strong> end up in prison with <strong>Rocket </strong><em>(Bradey Cooper)</em>, <strong>Groot </strong><em>(Vin Diesel)</em>, and <strong>Drax </strong><em>(Dave Bautista)</em>. Gamora reveals her plan to <strong>betray</strong> Ronan, and they <strong>escape</strong> the prison altogether.<br><br>They take the Orb to the <strong>Collector</strong>, who reveals that it is the <strong>Power Stone</strong>. With the help of the <strong>Ravagers</strong> and the <strong>Nova Corps</strong>, they fight Ronan&#x27;s force. <br><br>In the end, using the force of the <strong>stone</strong>, the <strong>Guardians of the Galaxy</strong> manage to <strong>kill Ronan</strong>. The <strong>stone</strong> is kept in safety with the <strong>Nova Corps</strong>.<br></p>
            {:else if sort == 5}
            <p class="paragraph">The <strong>fifth</strong> movie brings the <strong>heroes</strong> <span class="text-span-2"><sub class="subscript">○</sub></span> together and introduces new characters: <strong>Pietro</strong> <em>(Aaron Taylor-Johnson)</em> and <strong>Wanda </strong><em>(Elizabeth Olsen) </em><strong> Maximoff</strong><em>,</em> and <strong>Vision</strong> <em>(Paul Bettany).</em><br><br>After the <strong>fall</strong> of the <strong>S.H.I.E.L.D</strong>, the <strong>Avengers</strong> are reunited to raid a <strong>Hydra</strong> facility to retrieve Loki&#x27;s scepter. Here they fight <strong>Pietro</strong> and <strong>Wanda</strong> and manage to get the scepter.<br><br><strong>Stark</strong> and <strong>Banner </strong><em></em>discover that the scepter holds a <strong>gem</strong>. With <span class="text-span"><strong class="bold-text-2">JARVIS</strong></span>, they create <strong>Ultron</strong>, a <strong>global defense</strong> program that decides that <strong>humanity</strong> must be <strong>eradicated</strong> to save <strong>Earth.</strong> <br><br><strong>Wanda</strong> and <strong>Pietro</strong> discover Ultron&#x27;s plan and <strong>turn against him</strong>. The <strong> Avengers</strong> discover that the gem is the <strong>Mind Stone</strong>; they create <strong>Vision.</strong><br><br>Together, they fight <strong>Ultron</strong> and win. In the process, the country is <strong>destroyed</strong>, and <strong><span class="text-span"><strong class="bold-text-2">Pietro</strong></span> dies</strong>. <strong>Hulk</strong> leaves Earth, and <strong>Steve</strong> and <strong>Natasha</strong> plan to train the <strong>new Avengers</strong>, including <strong>Rhodes</strong>, <strong>Vision</strong>, <strong>Sam</strong>, and <strong>Wanda</strong>.<br><br><strong>Thanos</strong> decides to retrieve the stones <strong>himself</strong>.<br></p>
            {:else if sort == 6}
            <p class="paragraph">The <strong>last</strong> movie of Phase Two is a lighter movie that introduces new characters: <strong>Scott Lang</strong> <em>(Paul Rudd)</em>, aka <strong>Ant-Man</strong>, <strong>Hope van Dyne</strong> <em>(Evangeline Lilly)</em>, and <strong>Hank Pym</strong> <em>(Michael Douglas).</em><br><br><strong>Hank Pym</strong> invented the Pym particles, capable of <strong>increasing</strong> or <strong>reducing</strong> <strong> mass</strong>, <strong>density</strong>, and <strong>strength</strong><strong>. </strong>He never <strong>shared</strong> his technology, fearing <strong>misuse, </strong>and decided to <strong>hide</strong> it.<strong> <br><br>Darren Cross</strong> <em>(Corey Stoll) </em>is replicating this technology by building the <strong>Yellowjacket</strong>. <strong><br><br>Scott Lang</strong> is released from prison but commits burglary again. He brakes into a house and steals a weird <strong>suit</strong>. He tries it on and accidentally <strong>shrinks</strong> to the size of an <strong>ant</strong>.<br><br>Against the will of his daughter, <strong>Hope</strong>, Hank <strong>manipulated</strong> Scott to steal the suit and be the <strong>next Ant-Man </strong>to <strong>destroy </strong>the <strong> Yellowjacket.</strong> After training and fighting with <strong>Falcon</strong>, Scott and his crew manage to stop <strong>Darren</strong>.<br><br>In the end, Hank shows <strong>Hope</strong> a new suit, the <strong>Wasp</strong>, and <strong>Sam</strong> mentions that he &quot;know a guy&quot; to <strong>Steve Rogers</strong>, who managed to find <strong>Bucky</strong>.<br></p>
          {/if}

          {:else}
          {#if sort == 1}
            <p class="paragraph"><strong>Civil War</strong> is the <strong>first movie</strong> of Phase Three and, by its <strong>scale</strong>, resembles more an <strong>Avengers</strong> movie than a <strong>Captain America</strong>.<br><br>The <strong>Sokovia Accords</strong> gives the UN more control over the <strong>Avengers</strong>. <strong>Stark</strong> is in <strong>favor</strong>, <strong>Rogers</strong> <strong>against</strong>.<br><br>A <strong>bomb</strong>, presumably planted by <strong>Bucky Barnes</strong>, <strong>kills</strong> the king of <strong>Wakanda</strong>. His son, <strong>T&#x27;Challa</strong>, the <strong>Black Panther</strong>, vows to kill Bucky. The real <strong>culprit</strong> is <strong>Zemo</strong>. <br><br><strong>Steve</strong>, <strong>Bucky</strong>, <strong>Sam</strong>, <strong>Wanda</strong>, <strong>Clint</strong>, and <strong>Scott</strong> are going <strong>against </strong><strong>orders</strong> to capture <strong>Zemo</strong>. <strong>Tony</strong>, <strong>Nathasha</strong>, <strong>T&#x27;Challa</strong>, <strong>James</strong>, <strong>Vision</strong>, and <strong>Peter</strong> are ordered to stop them. <br> <br>Thanks to <strong>Natasha</strong>, <strong>Steve</strong> and <strong>Bucky </strong><strong>escape</strong>. <strong>Rhodes</strong> becomes partially <strong>paralyzed</strong>, and <strong>Steve&#x27;s</strong> crew is <strong>imprisoned</strong>. <strong>Tony</strong> goes after <strong>Steve</strong> and discovers that <strong>Bucky</strong> is responsible for his parent&#x27;s <strong>death</strong><strong></strong>. After a fight, <strong>Steve</strong> stops Tony, <strong>abandons</strong> his shield, and becomes a <strong>fugitive</strong>.<br><br><strong>Barnes</strong> is granted <strong>asylum</strong> in <strong>Wakanda</strong>.<br></p>
            {:else if sort == 2}
            <p class="paragraph">The second movie introduces a new important character, <strong>Dr. Strange</strong>, and an <strong>Infinity Stone</strong>.<br><br><strong>Stephen Strange</strong>, a famous <strong>neurosurgeon</strong>, <strong>loses</strong> the ability to use his <strong>hand</strong> in a <strong>car crash</strong>. Seeking a <strong>cure</strong>, Strange goes to <strong>Kamar-Taj</strong>.<br><br>With the help of the <strong>Ancient One </strong><em>(Tilda Swinton)</em>, <strong>Mordo </strong><em>(Chiwetel Ejiofor)</em>, and <strong>Wong </strong><em>(Benedict Wong)</em>, <strong>Strange</strong> learns about the <strong>Sanctums</strong> shielding the Earth, the <strong>sorcerers</strong> tasked to protect them, and the <strong>Eye of Agamotto</strong> that can bend <strong>time</strong>.<br><br><strong>Kaecilius </strong><em>(Mads Mikkelsen)</em>, a former student of <strong>Kamar-Taj</strong>, contacts <strong>Dormammu</strong>, who promises him <strong>eternal life </strong>for merging the Earth with the <strong>Dark Dimension</strong>. <br><br><strong>Kaecilius</strong> destroys the <strong>Sanctums</strong> and <strong>kills</strong> the <strong>Ancient One</strong>. As the Dark Dimension engulfs Earth, Strange uses the <strong>Eye of Agamotto</strong> to trap himself and <strong>Dormammu</strong> in an <strong>infinite </strong><strong>loop</strong>. Dormammu accepts to leave Earth <strong>alone</strong>.<br><br>In the end, the <strong>Eye of Agamotto</strong> is revealed to be an <strong>Infinity Stone</strong>, and <strong>Strange</strong> accepts to help <strong>Thor</strong> and <strong>Loki</strong> to find <strong>Odin</strong>. <br></p>
            {:else if sort == 3}
            <p class="paragraph">In the <strong>third</strong> movie of <strong>Phase Three</strong>, we reunite with the <strong>Guardians of the Galaxy</strong>!<br><br>After <strong>stealing</strong> the batteries they were supposed to protect in exchange for <strong>Nebula</strong> <em>(Karen Gillan)</em>, the Guardians are <strong>attacked</strong>. They end up on a planet where they meet <strong>Ego</strong> <em>(Kurt Russell)</em>, a <strong>Celestial</strong> and <strong>Peter Quill&#x27;s</strong><em>(Chris Pratt)</em> <strong>father</strong>. <br><br><strong>Yondu </strong><em>(Michael Rooker)</em>, who <strong>abducted</strong> Peter as a kid, is hired to <strong>capture</strong> the Guardians. Meanwhile, Quill travels to Ego&#x27;s <strong>planet</strong> and meets <strong>Mantis</strong> <em>(Pom Klementieff)</em>.<br><br>Ego reveals his <strong>goal</strong>. To <strong>expand</strong>, he needs the power of <strong>another Celestial</strong>. To that end, he conceived <strong>progeny</strong> in countless worlds. Ego is the reason why Peter was <strong>abducted</strong> and his <strong>mother killed</strong>. <br><br>The <strong>Guardians</strong>, <strong>Mantis</strong>, <strong>Yondu</strong>, and <strong>Nebula</strong>, team up to fight and <strong> kill Ego</strong>. <strong>Yondu</strong> <strong>sacrifices</strong> to save Peter. The Guardians and the Ravager gather to give him proper funeral. <br><br> <strong>Mantis</strong> joins the Guardians, and <strong>Nebula</strong> resumes her quest to kill <strong>Thanos</strong>. <strong>Peter</strong> and <strong>Gamora </strong><em>(Zoe Saldaña)</em> are now together. <br></p>
            {:else if sort == 4}
            <p class="paragraph">After being introduced in <strong>Civil War</strong>, it is time for <strong>Peter Parker</strong>, aka <strong>Spider-Man</strong>, to have his movie, the <strong>fourth</strong> of <strong>Phase Three</strong>. <br><br>In 2012, <strong>Adrian Toomes&#x27;s</strong> <em>(Michael Keaton)</em> company was hired to <strong>clean</strong> New York. After <strong>losing</strong> the <strong>contract</strong>, he started creating and <strong>selling weapons</strong>. <br><br>After the event of <strong>Civil War</strong>, <strong>Parker</strong> continues to <strong>fight crimes</strong>. One day, Parker intercepts a weapons deal, but <strong>Toomes</strong> arrives and uses his <strong>Vulture</strong> suit to <strong>fight him</strong>. <br><br><strong>Stark</strong> rescues <strong>Parker</strong> and asks him to <strong>stop pursuing</strong> the criminals. Later, Parker <strong>fights</strong> Toomes again and puts <strong>many people</strong> in <strong>danger</strong>. Stark <strong>takes back</strong> Parker&#x27;s suit as <strong>punishment</strong>. <br><br>Eventually, Parker learns that Toomes plans to <strong>steal</strong> weapons from the <strong>Avengers Tower</strong> and manages to <strong>stop</strong> him. <br><br>In the end, Parker <strong>declines</strong> Stark&#x27;s invitation to <strong>join</strong> the <strong>Avengers</strong>. Stark <strong>returns</strong> him the <strong>Spider-Man</strong> suit.<br></p>
            {:else if sort == 5}
            <p class="paragraph">Thor is back in the <strong>fifth</strong> movie of Phase Three! <br><br>With the help of <strong>Stephen Strange</strong>, <strong>Thor</strong> and <strong>Loki</strong> <strong>locate</strong> their father, <strong>Odin</strong>, in Norway. There, he <strong>dies</strong>, freeing <strong>Hela</strong> <em>(Cate Blanchett)</em>. She is Odin&#x27;s first child and was <strong>imprisoned</strong> after becoming too <strong>ambitious</strong> and <strong>powerful</strong>. <br><br>Hella <strong>destroys</strong> Thor&#x27;s <strong>hammer</strong> and takes <strong>control</strong> of <strong>Asgard</strong>. Thor ends up on Sakaar where he&#x27;s enslaved by <strong>Valkyrie</strong> <em>(Tessa Thompson)</em> and forced to <strong>compete</strong> in a fight contest. His <strong>opponent</strong> is his friend from work, the <strong>Hulk</strong>. <br><br>Thor <strong>convinces</strong> Hulk and Valkyrie to <strong>help</strong> him <strong>save</strong> Asgard. Together, they manage to go to Asgard, where they <strong>fight</strong> Hela&#x27;s forces. <strong>Loki</strong> arrives and helps them <strong>rescue</strong> the citizens.<br><br>Thor sends Loki to revive the fire demon <strong>Surtur</strong>, who brings the prophesied <strong>Ragnarok</strong>, <strong>destroys</strong> Asgard, and <strong>kills Hela</strong>. <br><br><strong>Thor</strong>, now <strong>king</strong> of the Asgardians, decides to take his people to <strong>Earth</strong> when a large <strong>spacecraft</strong> intercepts their vessel.<br></p>
            {:else if sort == 6}
            <p class="paragraph"><strong>Black Panther</strong> is the <strong>highest ranked</strong> movie of all MCU and expands on the <strong>eponymous</strong> character introduced in <strong>Civil War</strong>.<br><br>In <strong>1992</strong>, <strong>T&#x27;Chaka</strong> <strong>killed</strong> his <strong>brother N&#x27;Jobu</strong> for helping <strong>Klaue </strong><em>(Andy Serkis)</em> steal <strong>vibranium</strong>. <br><br><strong>T&#x27;Challa </strong><em>(Chadwick Boseman)</em><strong>,</strong> now <strong>king</strong> of Wakanda, tries to arrest Klaue, but <strong>Erik Stevens</strong> <em>(Michael B. Jordan)</em> manages to <strong>extract</strong> him. T&#x27;Challa learns that Erik, aka <strong>Killmonger</strong>, is <strong>N&#x27;Jobu&#x27;s son</strong>.<br><br>Killmonger <strong>kills</strong> Klaue, takes his body to Wakanda, and <strong>challenges</strong> T&#x27;Challa to <strong>ritual combat</strong>. T&#x27;Challa <strong>falls</strong> into a <strong>waterfall</strong> to his presumed <strong>death</strong>.<br><br>T&#x27;Challa is <strong>rescued</strong> and returns to <strong>fight</strong>. He manages to <strong>stab</strong> Killmonger, who <strong>refuses</strong> to be <strong>healed</strong>, preferring to <strong>die</strong> a <strong>free man</strong> rather than being <strong>enchained</strong>.<br><br>In the end, T&#x27;Challa <strong>reveals</strong> Wakanda&#x27;s true nature to the <strong>world</strong>, and <strong>Shuri </strong><em>(Letitia Wright)</em>,<strong> </strong>helps <strong>Bucky Barnes </strong>with his recovery.<br></p>
            {:else if sort == 7}
            <p class="paragraph"><strong>Infinity war </strong>is the <strong>seventh</strong> movie of <strong>Phase Three</strong>, <strong>tying</strong> almost all <strong>previous films</strong> and <strong>heroes</strong> <strong>together</strong>.<br><br>The movie starts when <strong>Thanos</strong>, having already acquired the <strong>Power Stone</strong>, intercepts <strong>Thor&#x27;s</strong> spaceship. He beats the <strong>Hulk</strong>, gets the <strong>Space Stone</strong>, and <strong>kills  <span class="text-span"><strong class="bold-text-2">Loki</strong></span></strong> and  <span class="text-span"><strong class="bold-text-2">Heimdall</strong></span>, who manages to <strong>send Hulk to Earth</strong>. <br><br><strong>Banner</strong> explains to <strong>Strange</strong>, <strong>Wong</strong>, and <strong>Stark</strong> that <strong>Thanos plans to destroy half of all life in the universe</strong> using the <strong>six Infinity Stones</strong>. At this moment, two of Thanos&#x27;s generals arrive to get the <strong>Time Stone</strong> and <strong>capture Strange</strong>. <strong>Peter Parker</strong> and <strong>Stark</strong> sneak aboard the <strong>general&#x27;s spaceship</strong>.<br><br>The <strong>Guardians of the Galaxy</strong> rescue <strong>Thor</strong>. With <strong>Rocket</strong> and <strong>Groot</strong>, he travels to <strong>Nidavellir</strong> to get a <strong>new weapon</strong>. The rest of the <strong>Guardians</strong> travel to the <strong>Collector</strong> to retrieve the <strong>Reality Stone</strong> but arrive <strong>too late</strong>.<br><br><strong>Thanos</strong>, now possessing three Stones, <strong>kidnaps Gamora</strong> and forces her to reveal the location of the <strong>Soul Stone</strong>. Thanos acquires his fourth Stone by <strong>sacrificing</strong> <strong>someone he loves</strong>, his daughter  <span class="text-span"><strong class="bold-text-2">Gamora</strong></span>. <br></p>
            {:else if sort == 8}
            <p class="paragraph"><br><strong>Wanda Maximoff</strong> and <strong>Vision</strong>, who exists thanks to the <strong>Mind Stone</strong>, are ambushed by Thanos&#x27;s generals. <strong>Steve Rogers</strong>, <strong>Natasha Romanoff</strong>, and <strong>Sam Wilson</strong> <strong>rescue</strong> them. The group travel to <strong>Wakanda</strong>, where they can <strong>extract</strong> the Stone <strong>without killing Vision</strong>.<br><br><strong>Stark</strong> and <strong>Parker</strong> <strong>rescue</strong> <strong>Strange</strong>. They land on <strong>Titan</strong>, where they meet <strong>Quill</strong>, <strong>Drax</strong>, <strong>Mantis</strong>, and <strong>Nebula</strong>. They make a plan to stop <strong>Thanos</strong> while <strong>Strange</strong> uses the Time Stone to <strong>view millions of possible</strong> futures, seeing only <strong>one</strong> in which they win. <br><br><strong>Thanos</strong> arrives, and the plan <strong>fails</strong> when <strong>Quill</strong> learns that Thanos <strong>killed</strong> Gamora. <strong>Strange</strong> <strong>offers</strong> the <strong>Time Stone</strong> in exchange for <strong>sparing Stark&#x27;s</strong> life.<br><br><strong>Thanos</strong> army <strong>invades</strong> Wakanda to get the last Stone. The <strong>Avengers</strong>, <strong>T&#x27;Challa</strong>, and <strong>Thor</strong>, armed with his new weapon, <strong>Stormbreaker</strong>, manage to <strong>repel</strong> the army. Unfortunately, <strong>Thanos arrives</strong> on the field, rapidly <strong>overpowers</strong> everyone, and finally <strong>rips the Stone</strong> from <strong> <span class="text-span"><strong class="bold-text-2">Vision</strong></span>&#x27;s</strong> forehead, <strong>killing him</strong>.<br><br>With all the stones, <strong>Thanos snaps</strong> his fingers and <strong>eradicates half of all life</strong> across the universe. <span class="text-span"><strong class="bold-text-2">Barnes</strong></span>, <span class="text-span"><strong class="bold-text-2">T&#x27;Challa</strong></span>, <span class="text-span"><strong class="bold-text-2">Groot</strong></span>, <span class="text-span"><strong class="bold-text-2">Maximoff</strong></span>, <span class="text-span"><strong class="bold-text-2">Wilson</strong></span>, <span class="text-span"><strong class="bold-text-2">Mantis</strong></span>, <span class="text-span"><strong class="bold-text-2">Drax</strong></span>, <span class="text-span"><strong class="bold-text-2">Quill</strong></span>, <span class="text-span"><strong class="bold-text-2">Strange</strong></span>, <span class="text-span"><strong class="bold-text-2">Parker</strong></span>, <span class="text-span"><strong class="bold-text-2">Maria Hill</strong></span>, and <span class="text-span"><strong class="bold-text-2">Nick Fury</strong></span> are <strong>gone</strong>. Before vanishing, Fury can send an <strong>emergency signal</strong>.<br></p>
            {:else if sort == 9}
            <p class="paragraph"><strong>Ant-Man</strong> is back in the <strong>eighth</strong> movie of <strong>Phase Three</strong>. The <strong>events</strong> of this movie are happening <strong>before</strong> or <strong>at the same time</strong> as <strong>Infinity War</strong>. <br><strong>‍</strong><br><strong>Hank Pym</strong> and <strong>Hope van Dyne</strong> try to open a tunnel to the <strong>Quantum Realm</strong> where Hope&#x27;s mother, <strong>Janet</strong>, may be <strong>trapped</strong>. <br><br>While retrieving a part needed for the tunnel, <strong>Hope</strong>, now wearing the <strong>Wasp</strong> outfit, is attacked by <strong>Ghost</strong>, who <strong>escapes</strong> with <strong>Pym&#x27;s lab</strong>.<br>‍<br><strong>Ghost</strong> is <strong>Ava Starr</strong>, the daughter of one of Pym&#x27;s former partners who <strong>died</strong> during an <strong>experiment</strong> that caused her to be <strong>dying</strong> and constantly <strong>in pain</strong>. She plans to use <strong>Janet&#x27;s quantum energy</strong> to <strong>cure</strong> her.<br>‍<br><strong>Lang</strong>, <strong>Pym</strong>, and <strong>Hope</strong> find the lab and <strong>Pym</strong> <strong>rescues</strong> <strong>Janet</strong>, who helps <strong>Ava</strong> to <strong>stabilize</strong> her condition and <strong>end</strong> her <strong>suffering</strong>.<br>‍<br>In the end, <strong>Pym</strong>, <strong>Lang</strong>, <strong>Hope</strong>, and <strong>Janet</strong> plan to return to the <strong>quantum realm</strong><strong></strong>. While <strong>Lang</strong> is in it, the other three <strong>vanishes</strong>, leaving <strong>Lang stuck</strong>.<br></p>
            {:else if sort == 10}
            <p class="paragraph">The <strong>ninth</strong> movie of <strong>Phase Three</strong> introduces a new <strong>hero</strong>, <strong>Carol Danvers </strong><em>(Brie Larson)</em>, aka <strong>Captain Marvel</strong>.<br>‍<br>In <strong>1995</strong>, during a mission, the <strong>shapeshifter</strong> Skrulls <strong>Talos </strong><em>(Ben Mendelsohn)</em> captures <strong>Vers</strong>, an <strong>amnesic </strong>Starforce member. She <strong>escapes</strong> and arrives on <strong>Earth</strong>, where she meets <strong>Nick Fury</strong>.<br>‍<br><strong>Vers</strong> discovers her name is <strong>Carol Danvers</strong> and that she <strong>presumably died</strong> while testing an <strong>engine</strong> designed by <strong>Dr. Lawson</strong>. <strong>Yon-Rogg </strong><em>(Jude Law)</em>, Carol&#x27;s <strong>mentor</strong>, <strong>killed </strong><strong>Dr. Lawson</strong>, and by <strong>destroying</strong> the <strong>engine</strong>, <strong>Danvers</strong> gained <strong>powers</strong> but <strong>lost her memory</strong>.<br>‍<br>Later, she learns that the <strong>Tesseract</strong> is the <strong>power source</strong> of Lawson&#x27;s engine. <strong>Danvers</strong> <strong>beats Yon-Rogg</strong> and gives <strong>Fury</strong> a <strong>pager</strong> to <strong>contact</strong> her in an <strong>emergency</strong>. She leaves Earth to help the <strong>Skrulls</strong> find a new <strong>home</strong>.<br>‍<br>After the event of <strong>Infinity War</strong>, the remaining <strong>Avengers</strong> are <strong>monitoring</strong> Fury&#x27;s <strong>pager</strong>. <strong>Denver</strong> appears, asking for <strong>Fury</strong>.<br></p>
            {:else if sort == 11}
            <p class="paragraph"><strong>Avengers: Endgame</strong> is the <strong>penultimate</strong> movie of the <strong>Infinity Saga</strong>. No other MCU movie has that many <strong>main characters</strong> and <strong>essential arc endings</strong>.<br>‍<br><strong>Danvers</strong> rescues <strong>Stark</strong> and <strong>Nebula</strong>. They reunite with the  survivors: <strong>Banner</strong>, <strong>Rogers</strong>, <strong>Thor</strong>, <strong>Romanoff</strong>, <strong>Rhodes</strong>, and <strong>Rocket</strong>. <br>‍<br>They locate <strong>Thanos</strong> and plan to use the <strong>Infinity Stones</strong> to bring <strong>everyone </strong><strong>back</strong>. Unfortunately, he has already <strong>destroyed</strong> them. <strong>Thor</strong> aims for the head and <strong>kills </strong><strong>him</strong>.<br>‍<br><strong>Five years later</strong>,<strong> Lang</strong> escapes from the <strong>Quantum Realm</strong> and <strong>theorizes</strong> that <strong>time travel is possible</strong>. <strong>Stark</strong> agrees to help build a <strong>time machine</strong> to find the <strong>Stones</strong> in the <strong>past</strong> and <strong>revert</strong> <strong>Thanos</strong>&#x27; actions. <strong>Banner</strong> recruits a <strong> Thor</strong>, and <strong>Romanoff</strong> recruits <strong>Barton</strong>.<br><br><strong>Banner</strong>, <strong>Lang</strong>, <strong>Rogers</strong>, and <strong>Stark </strong><strong>time-travel</strong> to <strong>2012</strong>. <strong>Banner</strong> gets the <strong>Time Stone</strong>, and <strong>Rogers</strong> the <strong>Mind Stone</strong>. <strong>Stark</strong> and <strong>Lang fail</strong> to get the <strong>Space Stone</strong> and allow<strong> 2012-Loki</strong> to <strong>escape</strong> with it, creating a <strong>Variant</strong>. <br></p>
            {:else if sort == 12}
            <p class="paragraph"><br><strong>Rogers</strong> and <strong>Stark</strong> travel to <strong>1970</strong>, where <br>they find an earlier version of <strong>Space Stone</strong>. <strong>Rocket</strong> and <strong>Thor</strong> travel to <strong>Asgard</strong> in <strong>2013</strong>, where they get the <strong>Reality Stone</strong> and retrieve Thor&#x27;s hammer, <strong>Mjolnir</strong>.  <span class="text-span"><strong class="bold-text-2">Romanoff</strong></span> <strong>sacrifices</strong> <strong>herself</strong> to allow <strong>Clint</strong> to get the <strong>Soul Stone</strong>. <br><br><strong>Nebula</strong> and <strong>Rhodes</strong> travel to <strong>2014</strong>, where they steal the <strong>Power Stone</strong>. <strong>2014-Thanos</strong> captures <strong>Nebula</strong> and learns of his <strong>success</strong> and the <strong>Avengers&#x27; plan</strong>. He sends <strong>2014-Nebula</strong> to the <strong>present</strong>.<br><br>In the <strong>present, Banner </strong>uses the six <strong>Stones</strong> to <strong>bring </strong><strong>everyone back</strong>. At the same time, <strong>2014-Nebula</strong> brings <strong>Thanos</strong> and his <strong>army</strong> into the <strong>present</strong> and <strong>kills her older self</strong>.<br>‍<br><strong>Thanos</strong> overpowers <strong>Stark</strong>, <strong>Thor</strong>, and <strong>Rogers</strong>, now worthy of holding <strong>Mjolnir</strong>. <strong>Strange</strong>, and the <strong>sorcerers</strong> arrive and open <strong>portals</strong> allowing <strong>everyone</strong> to <strong>come back</strong> and <strong>fight</strong>.<br>‍<br><strong>Thanos</strong> manages to get the <strong>Stones</strong> again, but at the last moment,  <span class="text-span"><strong class="bold-text-2">Stark</strong></span> <strong>steals them</strong> and, <strong>at the cost of his life</strong>, uses them to <strong>stop Thanos</strong>.<br>‍<br><strong>Thor</strong> joins the <strong>Guardians</strong>, and <strong>Rogers</strong> returns to the <strong>past</strong> to get the <strong>Stones</strong> to their <strong>proper timeline</strong>. He <strong>returns</strong> to the <strong>present</strong> as an <strong>older man</strong> and passes his <strong>shield</strong> to <strong>Sam Wilson</strong>. Steve decided to <strong>spend his life</strong> with his <strong>love</strong>, <strong>Peggy Carter</strong>. <br></p>
            {:else if sort == 13}
            <p class="paragraph"><strong>Concluding</strong> the <strong>Infinity Saga</strong> <em>(and this project for now)</em>, <strong>Spider-Man: Far From Home</strong> explores <strong>Parker&#x27;s</strong> <strong>future</strong> without <strong>Tony Stark</strong>.<br>‍<br>Parker&#x27;s school organizes a <strong>trip</strong> to <strong>Europe</strong>. In <strong>Venice</strong>, <strong>Parker</strong> fights an <strong>Elemental</strong> alongside <strong>Quentin Beck</strong> <em>(Jake Gyllenhaal)</em>, a  <strong>powerful </strong><strong>hero</strong> from <strong>another universe</strong>.<br>‍<br><strong>Fury</strong> gives <strong>Parker</strong> <strong>Stark&#x27;s glasses</strong>, containing <strong>EDITH</strong>, an <strong>AI</strong> with access to <strong>orbital weapons</strong>. Eventually, <strong>Parker </strong>gives the <strong>glasses</strong> to <strong>Beck</strong>.<br>‍<br><strong>Beck</strong> was using <strong>drones </strong>to <strong>simulate</strong> his <strong>powers</strong> and the <strong>Elementals</strong>. He plans to use <strong>EDITH</strong> to become an <strong>Avenger</strong>. <strong>MJ</strong> <em>(Zendaya)</em> discovers that <strong>Parker</strong> is <strong>Spider-Man</strong>. <br>‍<br>In <strong>London</strong>, <strong>Peter</strong> regains <strong>control</strong> of <strong>EDITH</strong> and <strong>defeats Beck</strong>. In the end, <strong>Jameson</strong> <em>(J. K. Simmons)</em> reveals <strong>Spider-Man&#x27;s secret identity</strong> to the world and <strong>accuses</strong> him of killing <strong>Beck</strong>. <strong>Fury</strong> and <strong>Hill</strong> were, in fact, <strong>Talos</strong> and <strong>Soren</strong> in <strong>disguise</strong>.<br></p>
        {/if}

        {/if}
      </div>
    </div>
  </div>
</div>