export default {
  "nodes": [
    { "id":"chrisprattpeterquill|starlord", "actorId":"chrispratt", "actorName": "Chris Pratt","movieList": "|phase2||guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"peterquill|starlord", "characterName":"Peter Quill | Star-Lord"},
    { "id":"cateblanchetthela", "actorId":"cateblanchett", "actorName": "Cate Blanchett","movieList": "|thorragnarok|", "type": "character", "characterId":"hela", "characterName":"Hela"},
    { "id":"zacharylevifandral", "actorId":"zacharylevi", "actorName": "Zachary Levi","movieList": "|phase1||phase2||thorragnarok|", "type": "character", "characterId":"fandral", "characterName":"Fandral"},
    { "id":"johnkaniatandwakanitchaka", "actorId":"johnkaniatandwakani", "actorName": "John Kani  Atandwa Kani","movieList": "|blackpanther|", "type": "character", "characterId":"tchaka", "characterName":"T'Chaka"},
    { "id":"chadwickbosemantchalla|blackpanther", "actorId":"chadwickboseman", "actorName": "Chadwick Boseman","movieList": "|captainamericacivilwar||blackpanther||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"tchalla|blackpanther", "characterName":"T'Challa | Black Panther"},
    { "id":"benedictcumberbatchdormammu", "actorId":"benedictcumberbatch", "actorName": "Benedict Cumberbatch","movieList": "|doctorstrange|", "type": "character", "characterId":"dormammu", "characterName":"Dormammu"},
    { "id":"angelabassettramonda", "actorId":"angelabassett", "actorName": "Angela Bassett","movieList": "|blackpanther||avengersendgame|", "type": "character", "characterId":"ramonda", "characterName":"Ramonda"},
    { "id":"zendayamichellemj", "actorId":"zendaya", "actorName": "Zendaya","movieList": "|spidermanhomecoming||spidermanfarfromhome|", "type": "character", "characterId":"michellemj", "characterName":"Michelle MJ"},
    { "id":"renerussofrigga", "actorId":"renerusso", "actorName": "Rene Russo","movieList": "|phase1||phase2||avengersendgame|", "type": "character", "characterId":"frigga", "characterName":"Frigga"},
    { "id":"williamhurtthaddeusthunderboltross", "actorId":"williamhurt", "actorName": "William Hurt","movieList": "|phase1||phase2||captainamericacivilwar||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"thaddeusthunderboltross", "characterName":"Thaddeus Thunderbolt Ross"},
    { "id":"cadewoodwardnathanielbarton", "actorId":"cadewoodward", "actorName": "Cade Woodward","movieList": "|avengersendgame|", "type": "character", "characterId":"nathanielbarton", "characterName":"Nathaniel Barton"},
    { "id":"hannahjohnkamenavastarr|ghost", "actorId":"hannahjohnkamen", "actorName": "Hannah JohnKamen","movieList": "|antmanandthewasp|", "type": "character", "characterId":"avastarr|ghost", "characterName":"Ava Starr | Ghost"},
    { "id":"johnkanitchaka", "actorId":"johnkani", "actorName": "John Kani","movieList": "|captainamericacivilwar|", "type": "character", "characterId":"tchaka", "characterName":"T'Chaka"},
    { "id":"sharonblynnsoren", "actorId":"sharonblynn", "actorName": "Sharon Blynn","movieList": "|captainmarvel||spidermanfarfromhome|", "type": "character", "characterId":"soren", "characterName":"Soren"},
    { "id":"hiroyukisanadaakihiko", "actorId":"hiroyukisanada", "actorName": "Hiroyuki Sanada","movieList": "|avengersendgame|", "type": "character", "characterId":"akihiko", "characterName":"Akihiko"},
    { "id":"chrisevanssteverogers|captainamerica", "actorId":"chrisevans", "actorName": "Chris Evans","movieList": "|phase1||phase2||captainamericacivilwar||spidermanhomecoming||avengersinfinitywar||captainmarvel||avengersendgame|", "type": "character", "characterId":"steverogers|captainamerica", "characterName":"Steve Rogers | Captain America"},
    { "id":"mileycyrusmainframe", "actorId":"mileycyrus", "actorName": "Miley Cyrus","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"mainframe", "characterName":"Mainframe"},
    { "id":"doncheadlejamesrhodeyrhodes|warmachine", "actorId":"doncheadle", "actorName": "Don Cheadle","movieList": "|phase1||phase2||captainamericacivilwar||avengersinfinitywar||captainmarvel||avengersendgame|", "type": "character", "characterId":"jamesrhodeyrhodes|warmachine", "characterName":"James Rhodey Rhodes | War Machine"},
    { "id":"gregghenrygrandpaquill", "actorId":"gregghenry", "actorName": "Gregg Henry","movieList": "|phase2||guardiansofthegalaxyvol2|", "type": "character", "characterId":"grandpaquill", "characterName":"Grandpa Quill"},
    { "id":"frankgrillobrockrumlow", "actorId":"frankgrillo", "actorName": "Frank Grillo","movieList": "|phase2||captainamericacivilwar||avengersendgame|", "type": "character", "characterId":"brockrumlow", "characterName":"Brock Rumlow"},
    { "id":"sebastianstanjamesbuckybarnes|wintersoldier", "actorId":"sebastianstan", "actorName": "Sebastian Stan","movieList": "|phase1||phase2||captainamericacivilwar||blackpanther||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"jamesbuckybarnes|wintersoldier", "characterName":"James Bucky Barnes | Winter Soldier"},
    { "id":"clarkgreggphilcoulson", "actorId":"clarkgregg", "actorName": "Clark Gregg","movieList": "|phase1||phase2||captainmarvel|", "type": "character", "characterId":"philcoulson", "characterName":"Phil Coulson"},
    { "id":"hopedavismariastark", "actorId":"hopedavis", "actorName": "Hope Davis","movieList": "|captainamericacivilwar|", "type": "character", "characterId":"mariastark", "characterName":"Maria Stark"},
    { "id":"andyserkisulyssesklaue", "actorId":"andyserkis", "actorName": "Andy Serkis","movieList": "|phase2||blackpanther|", "type": "character", "characterId":"ulyssesklaue", "characterName":"Ulysses Klaue"},
    { "id":"raystevensonvolstagg", "actorId":"raystevenson", "actorName": "Ray Stevenson","movieList": "|phase1||phase2||thorragnarok|", "type": "character", "characterId":"volstagg", "characterName":"Volstagg"},
    { "id":"jbsmoovejuliusdell", "actorId":"jbsmoove", "actorName": "J B Smoove","movieList": "|spidermanfarfromhome|", "type": "character", "characterId":"juliusdell", "characterName":"Julius Dell"},
    { "id":"zolawilliamsyama", "actorId":"zolawilliams", "actorName": "Zola Williams","movieList": "|blackpanther||avengersinfinitywar|", "type": "character", "characterId":"yama", "characterName":"Yama"},
    { "id":"karengillannebula", "actorId":"karengillan", "actorName": "Karen Gillan","movieList": "|phase2||guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"nebula", "characterName":"Nebula"},
    { "id":"paulruddscottlang|antman", "actorId":"paulrudd", "actorName": "Paul Rudd","movieList": "|phase2||captainamericacivilwar||antmanandthewasp||avengersendgame|", "type": "character", "characterId":"scottlang|antman", "characterName":"Scott Lang | Ant-Man"},
    { "id":"chiwetelejioforkarlmordo", "actorId":"chiwetelejiofor", "actorName": "Chiwetel Ejiofor","movieList": "|doctorstrange|", "type": "character", "characterId":"karlmordo", "characterName":"Karl Mordo"},
    { "id":"jjtotahseymour", "actorId":"jjtotah", "actorName": "J J Totah","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"seymour", "characterName":"Seymour"},
    { "id":"jacobbatalonnedleeds", "actorId":"jacobbatalon", "actorName": "Jacob Batalon","movieList": "|spidermanhomecoming||avengersinfinitywar||avengersendgame||spidermanfarfromhome|", "type": "character", "characterId":"nedleeds", "characterName":"Ned Leeds"},
    { "id":"jksimmonsjjonahjameson", "actorId":"jksimmons", "actorName": "J K Simmons","movieList": "|spidermanfarfromhome|", "type": "character", "characterId":"jjonahjameson", "characterName":"J Jonah Jameson"},
    { "id":"madsmikkelsenkaecilius", "actorId":"madsmikkelsen", "actorName": "Mads Mikkelsen","movieList": "|doctorstrange|", "type": "character", "characterId":"kaecilius", "characterName":"Kaecilius"},
    { "id":"tommyflanagantullk", "actorId":"tommyflanagan", "actorName": "Tommy Flanagan","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"tullk", "characterName":"Tullk"},
    { "id":"chrissullivantaserface", "actorId":"chrissullivan", "actorName": "Chris Sullivan","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"taserface", "characterName":"Taserface"},
    { "id":"tessathompsonvalkyrie", "actorId":"tessathompson", "actorName": "Tessa Thompson","movieList": "|thorragnarok||avengersendgame|", "type": "character", "characterId":"valkyrie", "characterName":"Valkyrie"},
    { "id":"joefriaoblo", "actorId":"joefria", "actorName": "Joe Fria","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"oblo", "characterName":"Oblo"},
    { "id":"michaelrosenbaummartinex", "actorId":"michaelrosenbaum", "actorName": "Michael Rosenbaum","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"martinex", "characterName":"Martinex"},
    { "id":"sterlingkbrownnjobu", "actorId":"sterlingkbrown", "actorName": "Sterling K Brown","movieList": "|blackpanther|", "type": "character", "characterId":"njobu", "characterName":"N'Jobu"},
    { "id":"scottadkinslucianaster", "actorId":"scottadkins", "actorName": "Scott Adkins","movieList": "|doctorstrange|", "type": "character", "characterId":"lucianaster", "characterName":"Lucian Aster"},
    { "id":"michaelchernusphineasmason|tinkerer", "actorId":"michaelchernus", "actorName": "Michael Chernus","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"phineasmason|tinkerer", "characterName":"Phineas Mason | Tinkerer"},
    { "id":"robertdowneyjrtonystark|ironman", "actorId":"robertdowneyjr", "actorName": "Robert Downey Jr","movieList": "|phase1||phase2||captainamericacivilwar||spidermanhomecoming||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"tonystark|ironman", "characterName":"Tony Stark | Iron Man"},
    { "id":"carriecoonproximamidnight", "actorId":"carriecoon", "actorName": "Carrie Coon","movieList": "|avengersinfinitywar|", "type": "character", "characterId":"proximamidnight", "characterName":"Proxima Midnight"},
    { "id":"tundeadebimpemrcobbwell", "actorId":"tundeadebimpe", "actorName": "Tunde Adebimpe","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"mrcobbwell", "characterName":"Mr Cobbwell"},
    { "id":"davebautistadraxthedestroyer", "actorId":"davebautista", "actorName": "Dave Bautista","movieList": "|phase2||guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"draxthedestroyer", "characterName":"Drax the Destroyer"},
    { "id":"judelawyonrogg", "actorId":"judelaw", "actorName": "Jude Law","movieList": "|captainmarvel|", "type": "character", "characterId":"yonrogg", "characterName":"Yon-Rogg"},
    { "id":"jeremyrennerclintbarton|hawkeye", "actorId":"jeremyrenner", "actorName": "Jeremy Renner","movieList": "|phase1||phase2||captainamericacivilwar||avengersendgame|", "type": "character", "characterId":"clintbarton|hawkeye", "characterName":"Clint Barton | Hawkeye"},
    { "id":"elizabetholsenwandamaximoff", "actorId":"elizabetholsen", "actorName": "Elizabeth Olsen","movieList": "|phase2||captainamericacivilwar||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"wandamaximoff", "characterName":"Wanda Maximoff"},
    { "id":"bensakamotocooperbarton", "actorId":"bensakamoto", "actorName": "Ben Sakamoto","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"cooperbarton", "characterName":"Cooper Barton"},
    { "id":"bradleycooperrocket", "actorId":"bradleycooper", "actorName": "Bradley Cooper","movieList": "|phase2||guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"rocket", "characterName":"Rocket"},
    { "id":"karlurbanskurge", "actorId":"karlurban", "actorName": "Karl Urban","movieList": "|thorragnarok|", "type": "character", "characterId":"skurge", "characterName":"Skurge"},
    { "id":"emilyvancampsharoncarter", "actorId":"emilyvancamp", "actorName": "Emily VanCamp","movieList": "|phase2||captainamericacivilwar|", "type": "character", "characterId":"sharoncarter", "characterName":"Sharon Carter"},
    { "id":"remyhiibraddavis", "actorId":"remyhii", "actorName": "Remy Hii","movieList": "|spidermanfarfromhome|", "type": "character", "characterId":"braddavis", "characterName":"Brad Davis"},
    { "id":"seangunnkraglinobfonteri", "actorId":"seangunn", "actorName": "Sean Gunn","movieList": "|phase2||guardiansofthegalaxyvol2||avengersendgame|", "type": "character", "characterId":"kraglinobfonteri", "characterName":"Kraglin Obfonteri"},
    { "id":"dawnmichellekingedith", "actorId":"dawnmichelleking", "actorName": "Dawn Michelle King","movieList": "|spidermanfarfromhome|", "type": "character", "characterId":"edith", "characterName":"EDITH"},
    { "id":"judygreermaggie", "actorId":"judygreer", "actorName": "Judy Greer","movieList": "|phase2||antmanandthewasp|", "type": "character", "characterId":"maggie", "characterName":"Maggie"},
    { "id":"annettebeningsupremeintelligence", "actorId":"annettebening", "actorName": "Annette Bening","movieList": "|captainmarvel|", "type": "character", "characterId":"supremeintelligence", "characterName":"Supreme Intelligence"},
    { "id":"randallparkjimmywoo", "actorId":"randallpark", "actorName": "Randall Park","movieList": "|antmanandthewasp|", "type": "character", "characterId":"jimmywoo", "characterName":"Jimmy Woo"},
    { "id":"selenisleyvamswarren", "actorId":"selenisleyva", "actorName": "Selenis Leyva","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"mswarren", "characterName":"Ms Warren"},
    { "id":"cobiesmuldersmariahill", "actorId":"cobiesmulders", "actorName": "Cobie Smulders","movieList": "|phase1||phase2||avengersinfinitywar||avengersendgame||spidermanfarfromhome|", "type": "character", "characterId":"mariahill", "characterName":"Maria Hill"},
    { "id":"abbyryderfortsoncassielang", "actorId":"abbyryderfortson", "actorName": "Abby Ryder Fortson","movieList": "|antmanandthewasp|", "type": "character", "characterId":"cassielang", "characterName":"Cassie Lang"},
    { "id":"tomhollandpeterparker|spiderman", "actorId":"tomholland", "actorName": "Tom Holland","movieList": "|captainamericacivilwar||spidermanhomecoming||avengersendgame||avengersinfinitywar||spidermanfarfromhome|", "type": "character", "characterId":"peterparker|spiderman", "characterName":"Peter Parker | Spider-Man"},
    { "id":"mikeescamillascrote", "actorId":"mikeescamilla", "actorName": "Mike Escamilla","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"scrote", "characterName":"Scrote"},
    { "id":"michaelbjordannjadaka", "actorId":"michaelbjordan", "actorName": "Michael B Jordan","movieList": "|blackpanther|", "type": "character", "characterId":"njadaka", "characterName":"Erik Stevens, N'Jadaka | Killmonger"},
    { "id":"tildaswintonancientone", "actorId":"tildaswinton", "actorName": "Tilda Swinton","movieList": "|doctorstrange||avengersendgame|", "type": "character", "characterId":"ancientone", "characterName":"Ancient One"},
    { "id":"peterbillingsleywilliamginterriva", "actorId":"peterbillingsley", "actorName": "Peter Billingsley","movieList": "|phase1||phase2||spidermanfarfromhome|", "type": "character", "characterId":"williamginterriva", "characterName":"William Ginter Riva"},
    { "id":"samuelljacksonnickfury", "actorId":"samuelljackson", "actorName": "Samuel L Jackson","movieList": "|phase1||phase2||avengersinfinitywar||captainmarvel||avengersendgame||spidermanfarfromhome|", "type": "character", "characterId":"nickfury", "characterName":"Nick Fury"},
    { "id":"numanacardimitri", "actorId":"numanacar", "actorName": "Numan Acar","movieList": "|spidermanfarfromhome|", "type": "character", "characterId":"dimitri", "characterName":"Dimitri"},
    { "id":"jeffgoldblumgrandmaster", "actorId":"jeffgoldblum", "actorName": "Jeff Goldblum","movieList": "|thorragnarok|", "type": "character", "characterId":"grandmaster", "characterName":"Grandmaster"},
    { "id":"vindieselgroot", "actorId":"vindiesel", "actorName": "Vin Diesel","movieList": "|phase2||guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"groot", "characterName":"Groot"},
    { "id":"lashanalynchmariarambeau", "actorId":"lashanalynch", "actorName": "Lashana Lynch","movieList": "|captainmarvel|", "type": "character", "characterId":"mariarambeau", "characterName":"Maria Rambeau"},
    { "id":"alexandrarachaelrabemorganstark", "actorId":"alexandrarachaelrabe", "actorName": "Alexandra Rachael Rabe","movieList": "|avengersendgame|", "type": "character", "characterId":"morganstark", "characterName":"Morgan Stark"},
    { "id":"hayleyatwellpeggycarter", "actorId":"hayleyatwell", "actorName": "Hayley Atwell","movieList": "|phase1||phase2||avengersendgame|", "type": "character", "characterId":"peggycarter", "characterName":"Peggy Carter"},
    { "id":"avarussolilabarton", "actorId":"avarusso", "actorName": "Ava Russo","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"lilabarton", "characterName":"Lila Barton"},
    { "id":"callanmulveyjackrollins", "actorId":"callanmulvey", "actorName": "Callan Mulvey","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"jackrollins", "characterName":"Jack Rollins"},
    { "id":"letitiawrightshuri", "actorId":"letitiawright", "actorName": "Letitia Wright","movieList": "|blackpanther||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"shuri", "characterName":"Shuri"},
    { "id":"ethandizontiny", "actorId":"ethandizon", "actorName": "Ethan Dizon","movieList": "|spidermanhomecoming||avengersinfinitywar|", "type": "character", "characterId":"tiny", "characterName":"Tiny"},
    { "id":"beniciodeltorotaneleertivan|thecollector", "actorId":"beniciodeltoro", "actorName": "Benicio del Toro","movieList": "|phase2||avengersinfinitywar|", "type": "character", "characterId":"taneleertivan|thecollector", "characterName":"Taneleer Tivan | The Collector"},
    { "id":"benjaminbrattjonathanpangborn", "actorId":"benjaminbratt", "actorName": "Benjamin Bratt","movieList": "|doctorstrange|", "type": "character", "characterId":"jonathanpangborn", "characterName":"Jonathan Pangborn"},
    { "id":"michaelstuhlbargnicodemuswest", "actorId":"michaelstuhlbarg", "actorName": "Michael Stuhlbarg","movieList": "|doctorstrange|", "type": "character", "characterId":"nicodemuswest", "characterName":"Nicodemus West"},
    { "id":"evanjonesretch", "actorId":"evanjones", "actorName": "Evan Jones","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"retch", "characterName":"Retch"},
    { "id":"stephenblackehartbrahl", "actorId":"stephenblackehart", "actorName": "Stephen Blackehart","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"brahl", "characterName":"Brahl"},
    { "id":"janeshiaadamsginyardnomble", "actorId":"janeshiaadamsginyard", "actorName": "Janeshia AdamsGinyard","movieList": "|blackpanther||avengersinfinitywar|", "type": "character", "characterId":"nomble", "characterName":"Nomble"},
    { "id":"johnpenickmrhapgood", "actorId":"johnpenick", "actorName": "John Penick","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"mrhapgood", "characterName":"Mr Hapgood"},
    { "id":"danaiguriraokoye", "actorId":"danaigurira", "actorName": "Danai Gurira","movieList": "|blackpanther||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"okoye", "characterName":"Okoye"},
    { "id":"gemmachanminnerva", "actorId":"gemmachan", "actorName": "Gemma Chan","movieList": "|captainmarvel|", "type": "character", "characterId":"minnerva", "characterName":"MinnErva"},
    { "id":"forestwhitakerdenzelwhitakerzuri", "actorId":"forestwhitakerdenzelwhitaker", "actorName": "Forest Whitaker  Denzel Whitaker","movieList": "|blackpanther|", "type": "character", "characterId":"zuri", "characterName":"Zuri"},
    { "id":"terrynotarycullobsidian", "actorId":"terrynotary", "actorName": "Terry Notary","movieList": "|avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"cullobsidian", "characterName":"Cull Obsidian"},
    { "id":"sylvesterstallonestakarogord", "actorId":"sylvesterstallone", "actorName": "Sylvester Stallone","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"stakarogord", "characterName":"Stakar Ogord"},
    { "id":"michaeljamesshawcorvusglaive", "actorId":"michaeljamesshaw", "actorName": "Michael James Shaw","movieList": "|avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"corvusglaive", "characterName":"Corvus Glaive"},
    { "id":"idriselbaheimdall", "actorId":"idriselba", "actorName": "Idris Elba","movieList": "|phase1||phase2||thorragnarok||avengersinfinitywar|", "type": "character", "characterId":"heimdall", "characterName":"Heimdall"},
    { "id":"jakegyllenhaalquentinbeck|mysterio", "actorId":"jakegyllenhaal", "actorName": "Jake Gyllenhaal","movieList": "|spidermanfarfromhome|", "type": "character", "characterId":"quentinbeck|mysterio", "characterName":"Quentin Beck | Mysterio"},
    { "id":"djimonhounsoukorath", "actorId":"djimonhounsou", "actorName": "Djimon Hounsou","movieList": "|phase2||captainmarvel|", "type": "character", "characterId":"korath", "characterName":"Korath"},
    { "id":"martinstarrrogerharrington", "actorId":"martinstarr", "actorName": "Martin Starr","movieList": "|phase1||phase2||spidermanhomecoming||spidermanfarfromhome|", "type": "character", "characterId":"rogerharrington", "characterName":"Roger Harrington"},
    { "id":"terencerosemorenarblik", "actorId":"terencerosemore", "actorName": "Terence Rosemore","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"narblik", "characterName":"Narblik"},
    { "id":"chrishemsworththor", "actorId":"chrishemsworth", "actorName": "Chris Hemsworth","movieList": "|phase1||phase2||doctorstrange||thorragnarok||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"thor", "characterName":"Thor"},
    { "id":"marisatomeimayparker", "actorId":"marisatomei", "actorName": "Marisa Tomei","movieList": "|captainamericacivilwar||spidermanhomecoming||avengersendgame||spidermanfarfromhome|", "type": "character", "characterId":"mayparker", "characterName":"May Parker"},
    { "id":"lupitanyongonakia", "actorId":"lupitanyongo", "actorName": "Lupita Nyongo","movieList": "|blackpanther|", "type": "character", "characterId":"nakia", "characterName":"Nakia"},
    { "id":"gwynethpaltrowvirginiapepperpotts", "actorId":"gwynethpaltrow", "actorName": "Gwyneth Paltrow","movieList": "|phase1||phase2||spidermanhomecoming||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"virginiapepperpotts", "characterName":"Virginia Pepper Potts"},
    { "id":"laurahaddockmeredithquill", "actorId":"laurahaddock", "actorName": "Laura Haddock","movieList": "|phase2||guardiansofthegalaxyvol2|", "type": "character", "characterId":"meredithquill", "characterName":"Meredith Quill"},
    { "id":"natalieportmanjanefoster", "actorId":"natalieportman", "actorName": "Natalie Portman","movieList": "|phase1||phase2||avengersendgame|", "type": "character", "characterId":"janefoster", "characterName":"Jane Foster"},
    { "id":"danielbrühlhelmutzemo", "actorId":"danielbrühl", "actorName": "Daniel Brühl","movieList": "|captainamericacivilwar|", "type": "character", "characterId":"helmutzemo", "characterName":"Helmut Zemo"},
    { "id":"kurtrussellego", "actorId":"kurtrussell", "actorName": "Kurt Russell","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"ego", "characterName":"Ego"},
    { "id":"divianladwauzman", "actorId":"divianladwa", "actorName": "Divian Ladwa","movieList": "|antmanandthewasp|", "type": "character", "characterId":"uzman", "characterName":"Uzman"},
    { "id":"tomhiddlestonloki", "actorId":"tomhiddleston", "actorName": "Tom Hiddleston","movieList": "|phase1||phase2||thorragnarok||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"loki", "characterName":"Loki"},
    { "id":"bokeemwoodbinehermanschultz|shocker", "actorId":"bokeemwoodbine", "actorName": "Bokeem Woodbine","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"hermanschultz|shocker", "characterName":"Herman Schultz | Shocker"},
    { "id":"taikawaititikorg", "actorId":"taikawaititi", "actorName": "Taika Waititi","movieList": "|thorragnarok||avengersendgame|", "type": "character", "characterId":"korg", "characterName":"Korg"},
    { "id":"michaelcerveriselihasstarr", "actorId":"michaelcerveris", "actorName": "Michael Cerveris","movieList": "|antmanandthewasp|", "type": "character", "characterId":"elihasstarr", "characterName":"Elihas Starr"},
    { "id":"jorgelendeborgjrjasonionello", "actorId":"jorgelendeborgjr", "actorName": "Jorge Lendeborg Jr","movieList": "|spidermanhomecoming||spidermanfarfromhome|", "type": "character", "characterId":"jasonionello", "characterName":"Jason Ionello"},
    { "id":"tadanobuasanohogun", "actorId":"tadanobuasano", "actorName": "Tadanobu Asano","movieList": "|phase1||phase2||thorragnarok|", "type": "character", "characterId":"hogun", "characterName":"Hogun"},
    { "id":"rachelmcadamschristinepalmer", "actorId":"rachelmcadams", "actorName": "Rachel McAdams","movieList": "|doctorstrange|", "type": "character", "characterId":"christinepalmer", "characterName":"Christine Palmer"},
    { "id":"moniquegandertonproximamidnight", "actorId":"moniqueganderton", "actorName": "Monique Ganderton","movieList": "|avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"proximamidnight", "characterName":"Proxima Midnight"},
    { "id":"tysimpkinsharleykeener", "actorId":"tysimpkins", "actorName": "Ty Simpkins","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"harleykeener", "characterName":"Harley Keener"},
    { "id":"elizabethdebickiayesha", "actorId":"elizabethdebicki", "actorName": "Elizabeth Debicki","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"ayesha", "characterName":"Ayesha"},
    { "id":"steveageegeftheravager", "actorId":"steveagee", "actorName": "Steve Agee","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"geftheravager", "characterName":"Gef the Ravager"},
    { "id":"jonfavreauharoldhappyhogan", "actorId":"jonfavreau", "actorName": "Jon Favreau","movieList": "|phase1||phase2||spidermanhomecoming||avengersendgame||spidermanfarfromhome|", "type": "character", "characterId":"haroldhappyhogan", "characterName":"Harold Happy Hogan"},
    { "id":"alfrewoodardmiriamsharpe", "actorId":"alfrewoodard", "actorName": "Alfre Woodard","movieList": "|captainamericacivilwar|", "type": "character", "characterId":"miriamsharpe", "characterName":"Miriam Sharpe"},
    { "id":"paulbettanyvision", "actorId":"paulbettany", "actorName": "Paul Bettany","movieList": "|phase2||captainamericacivilwar||avengersinfinitywar|", "type": "character", "characterId":"vision", "characterName":"Vision"},
    { "id":"brielarsoncaroldanvers|captainmarvel", "actorId":"brielarson", "actorName": "Brie Larson","movieList": "|captainmarvel||avengersendgame|", "type": "character", "characterId":"caroldanvers|captainmarvel", "characterName":"Carol Danvers | Captain Marvel"},
    { "id":"winstondukembaku", "actorId":"winstonduke", "actorName": "Winston Duke","movieList": "|blackpanther||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"mbaku", "characterName":"M'Baku"},
    { "id":"pomklementieffmantis", "actorId":"pomklementieff", "actorName": "Pom Klementieff","movieList": "|guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"mantis", "characterName":"Mantis"},
    { "id":"topowresniwirohamir", "actorId":"topowresniwiro", "actorName": "Topo Wresniwiro","movieList": "|doctorstrange|", "type": "character", "characterId":"hamir", "characterName":"Hamir"},
    { "id":"benedictcumberbatchstephenstrange", "actorId":"benedictcumberbatch", "actorName": "Benedict Cumberbatch","movieList": "|doctorstrange||thorragnarok||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"stephenstrange", "characterName":"Stephen Strange"},
    { "id":"laurencefishburnebillfoster", "actorId":"laurencefishburne", "actorName": "Laurence Fishburne","movieList": "|antmanandthewasp|", "type": "character", "characterId":"billfoster", "characterName":"Bill Foster"},
    { "id":"peterdinklageeitri", "actorId":"peterdinklage", "actorName": "Peter Dinklage","movieList": "|avengersinfinitywar|", "type": "character", "characterId":"eitri", "characterName":"Eitri"},
    { "id":"angouriericebettybrant", "actorId":"angourierice", "actorName": "Angourie Rice","movieList": "|spidermanhomecoming||spidermanfarfromhome|", "type": "character", "characterId":"bettybrant", "characterName":"Betty Brant"},
    { "id":"rachelhousetopaz", "actorId":"rachelhouse", "actorName": "Rachel House","movieList": "|thorragnarok|", "type": "character", "characterId":"topaz", "characterName":"Topaz"},
    { "id":"tiffanyespensencindy", "actorId":"tiffanyespensen", "actorName": "Tiffany Espensen","movieList": "|spidermanhomecoming||avengersinfinitywar|", "type": "character", "characterId":"cindy", "characterName":"Cindy"},
    { "id":"lauraharrierliz", "actorId":"lauraharrier", "actorName": "Laura Harrier","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"liz", "characterName":"Liz"},
    { "id":"sethgreenhowardtheduck", "actorId":"sethgreen", "actorName": "Seth Green","movieList": "|phase2||guardiansofthegalaxyvol2|", "type": "character", "characterId":"howardtheduck", "characterName":"Howard the Duck"},
    { "id":"algenisperezsotoattlass", "actorId":"algenisperezsoto", "actorName": "Algenis Perez Soto","movieList": "|captainmarvel|", "type": "character", "characterId":"attlass", "characterName":"AttLass"},
    { "id":"michellepfeifferjanetvandyne", "actorId":"michellepfeiffer", "actorName": "Michelle Pfeiffer","movieList": "|phase2||antmanandthewasp||avengersendgame|", "type": "character", "characterId":"janetvandyne", "characterName":"Janet van Dyne"},
    { "id":"loganmarshallgreenjacksonbrice|shocker", "actorId":"loganmarshallgreen", "actorName": "Logan MarshallGreen","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"jacksonbrice|shocker", "characterName":"Jackson Brice | Shocker"},
    { "id":"tiptiharrisdave", "actorId":"tiptiharris", "actorName": "Tip TI Harris","movieList": "|phase2||antmanandthewasp|", "type": "character", "characterId":"dave", "characterName":"Dave"},
    { "id":"tynedalyannemariehoag", "actorId":"tynedaly", "actorName": "Tyne Daly","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"annemariehoag", "characterName":"Anne Marie Hoag"},
    { "id":"hemkymaderamrdelmar", "actorId":"hemkymadera", "actorName": "Hemky Madera","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"mrdelmar", "characterName":"Mr Delmar"},
    { "id":"markruffalobrucebanner|hulk", "actorId":"markruffalo", "actorName": "Mark Ruffalo","movieList": "|phase1||phase2||thorragnarok||avengersinfinitywar||captainmarvel||avengersendgame|", "type": "character", "characterId":"brucebanner|hulk", "characterName":"Bruce Banner | Hulk"},
    { "id":"kennethchoiprincipalmorita", "actorId":"kennethchoi", "actorName": "Kenneth Choi","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"principalmorita", "characterName":"Principal Morita"},
    { "id":"jamesdarcyedwinjarvis", "actorId":"jamesdarcy", "actorName": "James DArcy","movieList": "|avengersendgame|", "type": "character", "characterId":"edwinjarvis", "characterName":"Edwin Jarvis"},
    { "id":"tomvaughanlawlorebonymaw", "actorId":"tomvaughanlawlor", "actorName": "Tom VaughanLawlor","movieList": "|avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"ebonymaw", "characterName":"Ebony Maw"},
    { "id":"bobbycannavalejimpaxton", "actorId":"bobbycannavale", "actorName": "Bobby Cannavale","movieList": "|phase2||antmanandthewasp|", "type": "character", "characterId":"jimpaxton", "characterName":"Jim Paxton"},
    { "id":"michaeldouglashankpym", "actorId":"michaeldouglas", "actorName": "Michael Douglas","movieList": "|phase2||antmanandthewasp||avengersendgame|", "type": "character", "characterId":"hankpym", "characterName":"Hank Pym"},
  
    { "id":"kerrycondonfriday", "actorId":"kerrycondon", "actorName": "Kerry Condon","movieList": "|phase2||captainamericacivilwar||spidermanhomecoming||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"friday", "characterName":"FRIDAY"},
    { "id":"nabiyahbelinda", "actorId":"nabiyahbe", "actorName": "Nabiyah Be","movieList": "|blackpanther|", "type": "character", "characterId":"linda", "characterName":"Linda"},
    { "id":"scarlettjohanssonnatasharomanoff|blackwidow", "actorId":"scarlettjohansson", "actorName": "Scarlett Johansson","movieList": "|phase1||phase2||captainamericacivilwar||avengersinfinitywar||captainmarvel||avengersendgame|", "type": "character", "characterId":"natasharomanoff|blackwidow", "characterName":"Natasha Romanoff | Black Widow"},
    { "id":"lindalouiseduantinaminoru", "actorId":"lindalouiseduan", "actorName": "Linda Louise Duan","movieList": "|doctorstrange|", "type": "character", "characterId":"tinaminoru", "characterName":"Tina Minoru"},
    { "id":"benmendelsohntalos", "actorId":"benmendelsohn", "actorName": "Ben Mendelsohn","movieList": "|captainmarvel||spidermanfarfromhome|", "type": "character", "characterId":"talos", "characterName":"Talos"},
    { "id":"michaelmandomacgargan", "actorId":"michaelmando", "actorName": "Michael Mando","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"macgargan", "characterName":"Mac Gargan"},
    { "id":"maximilianohernándezjaspersitwell", "actorId":"maximilianohernández", "actorName": "Maximiliano Hernández","movieList": "|phase1||phase2||avengersendgame|", "type": "character", "characterId":"jaspersitwell", "characterName":"Jasper Sitwell"},
    { "id":"florencekasumbaayo", "actorId":"florencekasumba", "actorName": "Florence Kasumba","movieList": "|captainamericacivilwar||blackpanther||avengersinfinitywar|", "type": "character", "characterId":"ayo", "characterName":"Ayo"},
    { "id":"michaelkeatonadriantoomes|vulture", "actorId":"michaelkeaton", "actorName": "Michael Keaton","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"adriantoomes|vulture", "characterName":"Adrian Toomes | Vulture"},
    { "id":"emmafuhrmanncassielang", "actorId":"emmafuhrmann", "actorName": "Emma Fuhrmann","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"cassielang", "characterName":"Cassie Lang"},
    { "id":"donaldgloveraarondavis", "actorId":"donaldglover", "actorName": "Donald Glover","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"aarondavis", "characterName":"Aaron Davis"},
    { "id":"abrahamattahabraham", "actorId":"abrahamattah", "actorName": "Abraham Attah","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"abraham", "characterName":"Abraham"},
    { "id":"anthonyhopkinsodin", "actorId":"anthonyhopkins", "actorName": "Anthony Hopkins","movieList": "|phase1||phase2||thorragnarok|", "type": "character", "characterId":"odin", "characterName":"Odin"},
    { "id":"vingrhamescharlie", "actorId":"vingrhames", "actorName": "Ving Rhames","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"charlie", "characterName":"Charlie"},
    { "id":"hannibalburesscoachwilson", "actorId":"hannibalburess", "actorName": "Hannibal Buress","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"coachwilson", "characterName":"Coach Wilson"},
    { "id":"johnslatteryhowardstark", "actorId":"johnslattery", "actorName": "John Slattery","movieList": "|phase1||phase2||captainamericacivilwar||avengersendgame|", "type": "character", "characterId":"howardstark", "characterName":"Howard Stark"},
    { "id":"michaelpeñaluis", "actorId":"michaelpeña", "actorName": "Michael Peña","movieList": "|phase2||antmanandthewasp|", "type": "character", "characterId":"luis", "characterName":"Luis"},
    { "id":"daviddastmalchiankurt", "actorId":"daviddastmalchian", "actorName": "David Dastmalchian","movieList": "|phase2||antmanandthewasp|", "type": "character", "characterId":"kurt", "characterName":"Kurt"},
    { "id":"evangelinelillyhopevandyne|wasp", "actorId":"evangelinelilly", "actorName": "Evangeline Lilly","movieList": "|phase2||antmanandthewasp||avengersendgame|", "type": "character", "characterId":"hopevandyne|wasp", "characterName":"Hope van Dyne | Wasp"},
    { "id":"annettebeningmarvellwendylawson", "actorId":"annettebening", "actorName": "Annette Bening","movieList": "|captainmarvel|", "type": "character", "characterId":"marvellwendylawson", "characterName":"MarVell  Wendy Lawson"},
    { "id":"robertredfordalexanderpierce", "actorId":"robertredford", "actorName": "Robert Redford","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"alexanderpierce", "characterName":"Alexander Pierce"},
    { "id":"michaelbarbiericharles", "actorId":"michaelbarbieri", "actorName": "Michael Barbieri","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"charles", "characterName":"Charles"},
    { "id":"joshbrolinthanos", "actorId":"joshbrolin", "actorName": "Josh Brolin","movieList": "|phase1||phase2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"thanos", "characterName":"Thanos"},
    { "id":"waltongogginssonnyburch", "actorId":"waltongoggins", "actorName": "Walton Goggins","movieList": "|antmanandthewasp|", "type": "character", "characterId":"sonnyburch", "characterName":"Sonny Burch"},
    { "id":"akiraakbarmonicarambeau", "actorId":"akiraakbar", "actorName": "Akira Akbar","movieList": "|captainmarvel|", "type": "character", "characterId":"monicarambeau", "characterName":"Monica Rambeau"},
    { "id":"danielkaluuyawkabi", "actorId":"danielkaluuya", "actorName": "Daniel Kaluuya","movieList": "|blackpanther|", "type": "character", "characterId":"wkabi", "characterName":"W'Kabi"},
    { "id":"benedictwongwong", "actorId":"benedictwong", "actorName": "Benedict Wong","movieList": "|doctorstrange||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"wong", "characterName":"Wong"},
    { "id":"leepaceronantheaccuser", "actorId":"leepace", "actorName": "Lee Pace","movieList": "|phase2||captainmarvel|", "type": "character", "characterId":"ronantheaccuser", "characterName":"Ronan the Accuser"},
    { "id":"tonyrevolorieugeneflashthompson", "actorId":"tonyrevolori", "actorName": "Tony Revolori","movieList": "|spidermanhomecoming||spidermanfarfromhome|", "type": "character", "characterId":"eugeneflashthompson", "characterName":"Eugene Flash Thompson"},
    { "id":"runetemtebronchar", "actorId":"runetemte", "actorName": "Rune Temte","movieList": "|captainmarvel|", "type": "character", "characterId":"bronchar", "characterName":"BronChar"},
    { "id":"jimmyurinehalfnut", "actorId":"jimmyurine", "actorName": "Jimmy Urine","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"halfnut", "characterName":"HalfNut"},
    { "id":"rossmarquandjohannschmidt|redskull", "actorId":"rossmarquand", "actorName": "Ross Marquand","movieList": "|phase1||phase2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"johannschmidt|redskull", "characterName":"Johann Schmidt | Red Skull"},
    { "id":"markanthonybrightondanieldrumm", "actorId":"markanthonybrighton", "actorName": "Mark Anthony Brighton","movieList": "|doctorstrange|", "type": "character", "characterId":"danieldrumm", "characterName":"Daniel Drumm"},
    { "id":"martinfreemaneverettkross", "actorId":"martinfreeman", "actorName": "Martin Freeman","movieList": "|captainamericacivilwar||blackpanther|", "type": "character", "characterId":"everettkross", "characterName":"Everett K Ross"},
    { "id":"zoesaldañagamora", "actorId":"zoesaldaña", "actorName": "Zoe Saldaña","movieList": "|phase2||guardiansofthegalaxyvol2||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"gamora", "characterName":"Gamora"},
    { "id":"michaelrookeryonduudonta", "actorId":"michaelrooker", "actorName": "Michael Rooker","movieList": "|phase2||guardiansofthegalaxyvol2|", "type": "character", "characterId":"yonduudonta", "characterName":"Yondu Udonta"},
    { "id":"garcellebeauvaisdoristoomes", "actorId":"garcellebeauvais", "actorName": "Garcelle Beauvais","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"doristoomes", "characterName":"Doris Toomes"},
    { "id":"jenniferconnellykaren", "actorId":"jenniferconnelly", "actorName": "Jennifer Connelly","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"karen", "characterName":"Karen"},
    { "id":"lindacardellinilaurabarton", "actorId":"lindacardellini", "actorName": "Linda Cardellini","movieList": "|phase2||avengersendgame|", "type": "character", "characterId":"laurabarton", "characterName":"Laura Barton"},
    { "id":"isabellaamarasally", "actorId":"isabellaamara", "actorName": "Isabella Amara","movieList": "|spidermanhomecoming||avengersinfinitywar|", "type": "character", "characterId":"sally", "characterName":"Sally"},
    { "id":"anthonymackiesamwilson|falcon", "actorId":"anthonymackie", "actorName": "Anthony Mackie","movieList": "|phase2||captainamericacivilwar||avengersinfinitywar||avengersendgame|", "type": "character", "characterId":"samwilson|falcon", "characterName":"Sam Wilson | Falcon"},
    { "id":"garyweeksfoster", "actorId":"garyweeks", "actorName": "Gary Weeks","movieList": "|spidermanhomecoming|", "type": "character", "characterId":"foster", "characterName":"Foster"},
    { "id":"clancybrownsurtur", "actorId":"clancybrown", "actorName": "Clancy Brown","movieList": "|thorragnarok|", "type": "character", "characterId":"surtur", "characterName":"Surtur"},
    { "id":"michelleyeohaletaogord", "actorId":"michelleyeoh", "actorName": "Michelle Yeoh","movieList": "|guardiansofthegalaxyvol2|", "type": "character", "characterId":"aletaogord", "characterName":"Aleta Ogord"},
    { "id":"sydellenoelxoliswa", "actorId":"sydellenoel", "actorName": "Sydelle Noel","movieList": "|blackpanther|", "type": "character", "characterId":"xoliswa", "characterName":"Xoliswa"},
    { "id":"captainmarvel", "name": "Captain Marvel", "type": "movie", "boxoffice":1128275263, "score":79, "releaseDate":"2019-03-08" },
    { "id":"spidermanfarfromhome", "name": "SpiderMan Far From Home", "type": "movie", "boxoffice":1131927996, "score":90, "releaseDate":"2019-07-02" },
    { "id":"antmanandthewasp", "name": "AntMan and the Wasp", "type": "movie", "boxoffice":622674139, "score":87, "releaseDate":"2018-07-06" },
    { "id":"doctorstrange", "name": "Doctor Strange", "type": "movie", "boxoffice":677718395, "score":89, "releaseDate":"2016-11-04" },
    { "id":"captainamericacivilwar", "name": "Captain America Civil War", "type": "movie", "boxoffice":1153296293, "score":90, "releaseDate":"2016-05-06" },
    { "id":"guardiansofthegalaxyvol2", "name": "Guardians of the Galaxy Vol 2", "type": "movie", "boxoffice":863756051, "score":85, "releaseDate":"2017-05-05" },
    { "id":"avengersendgame", "name": "Avengers Endgame", "type": "movie", "boxoffice":2797800564, "score":94, "releaseDate":"2019-04-26" },
    { "id":"avengersinfinitywar", "name": "Avengers Infinity War", "type": "movie", "boxoffice":2048359754, "score":85, "releaseDate":"2018-04-27" },
    { "id":"blackpanther", "name": "Black Panther", "type": "movie", "boxoffice":1347280161, "score":96, "releaseDate":"2018-02-16" },
    { "id":"thorragnarok", "name": "Thor Ragnarok", "type": "movie", "boxoffice":853977126, "score":93, "releaseDate":"2017-11-03" },
    { "id":"spidermanhomecoming", "name": "SpiderMan Homecoming", "type": "movie", "boxoffice":880166924, "score":92, "releaseDate":"2017-07-07" },
    { "id":"phasetwo", "name": "Phase Two", "type": "movie", "boxoffice":0, "score":0, "releaseDate":"None" }
    ],
    "links": [
    { "source":"avengersendgame", "target":"tildaswintonancientone"},
    { "source":"phasetwo", "target":"lindacardellinilaurabarton"},
    { "source":"phasetwo", "target":"evangelinelillyhopevandyne|wasp"},
    { "source":"avengersinfinitywar", "target":"robertdowneyjrtonystark|ironman"},
    { "source":"guardiansofthegalaxyvol2", "target":"pomklementieffmantis"},
    { "source":"spidermanfarfromhome", "target":"cobiesmuldersmariahill"},
    { "source":"spidermanfarfromhome", "target":"angouriericebettybrant"},
    { "source":"thorragnarok", "target":"benedictcumberbatchstephenstrange"},
    { "source":"guardiansofthegalaxyvol2", "target":"mileycyrusmainframe"},
    
    { "source":"captainamericacivilwar", "target":"anthonymackiesamwilson|falcon"},
    { "source":"antmanandthewasp", "target":"paulruddscottlang|antman"},
    
    { "source":"avengersendgame", "target":"gwynethpaltrowvirginiapepperpotts"},
    { "source":"spidermanhomecoming", "target":"ethandizontiny"},
    { "source":"doctorstrange", "target":"chrishemsworththor"},
    { "source":"captainamericacivilwar", "target":"johnkanitchaka"},
    { "source":"guardiansofthegalaxyvol2", "target":"jimmyurinehalfnut"},
    { "source":"avengersendgame", "target":"markruffalobrucebanner|hulk"},
    { "source":"captainmarvel", "target":"akiraakbarmonicarambeau"},
    { "source":"phasetwo", "target":"maximilianohernándezjaspersitwell"},
    { "source":"doctorstrange", "target":"topowresniwirohamir"},
    { "source":"spidermanfarfromhome", "target":"marisatomeimayparker"},
    { "source":"spidermanhomecoming", "target":"marisatomeimayparker"},
    { "source":"avengersendgame", "target":"avarussolilabarton"},
    { "source":"avengersinfinitywar", "target":"kerrycondonfriday"},
    { "source":"spidermanfarfromhome", "target":"tonyrevolorieugeneflashthompson"},
    { "source":"phasetwo", "target":"michaelpeñaluis"},
    { "source":"antmanandthewasp", "target":"michaelcerveriselihasstarr"},
    
    { "source":"antmanandthewasp", "target":"judygreermaggie"},
    
    { "source":"captainamericacivilwar", "target":"sebastianstanjamesbuckybarnes|wintersoldier"},
    { "source":"captainamericacivilwar", "target":"robertdowneyjrtonystark|ironman"},
    { "source":"avengersendgame", "target":"moniquegandertonproximamidnight"},
    { "source":"phasetwo", "target":"michellepfeifferjanetvandyne"},
    { "source":"guardiansofthegalaxyvol2", "target":"kurtrussellego"},
    { "source":"guardiansofthegalaxyvol2", "target":"steveageegeftheravager"},
    
    { "source":"phasetwo", "target":"peterbillingsleywilliamginterriva"},
    { "source":"captainamericacivilwar", "target":"martinfreemaneverettkross"},
    { "source":"avengersinfinitywar", "target":"tomvaughanlawlorebonymaw"},
    
    { "source":"avengersinfinitywar", "target":"chrisevanssteverogers|captainamerica"},
    { "source":"spidermanhomecoming", "target":"donaldgloveraarondavis"},
    { "source":"spidermanhomecoming", "target":"kerrycondonfriday"},
    { "source":"doctorstrange", "target":"scottadkinslucianaster"},
    { "source":"captainmarvel", "target":"djimonhounsoukorath"},
    { "source":"spidermanhomecoming", "target":"michaelkeatonadriantoomes|vulture"},
    { "source":"captainmarvel", "target":"sharonblynnsoren"},
    { "source":"phasetwo", "target":"hayleyatwellpeggycarter"},
    { "source":"phasetwo", "target":"markruffalobrucebanner|hulk"},
    
    { "source":"guardiansofthegalaxyvol2", "target":"sethgreenhowardtheduck"},
    { "source":"guardiansofthegalaxyvol2", "target":"chrissullivantaserface"},
    { "source":"avengersinfinitywar", "target":"michaeljamesshawcorvusglaive"},
    { "source":"avengersendgame", "target":"johnslatteryhowardstark"},
    { "source":"doctorstrange", "target":"benjaminbrattjonathanpangborn"},
    { "source":"spidermanhomecoming", "target":"tundeadebimpemrcobbwell"},
    
    { "source":"avengersendgame", "target":"jamesdarcyedwinjarvis"},
    { "source":"phasetwo", "target":"scarlettjohanssonnatasharomanoff|blackwidow"},
    { "source":"phasetwo", "target":"anthonyhopkinsodin"},
    { "source":"spidermanfarfromhome", "target":"jonfavreauharoldhappyhogan"},
    { "source":"avengersendgame", "target":"callanmulveyjackrollins"},
    { "source":"thorragnarok", "target":"karlurbanskurge"},
    { "source":"captainmarvel", "target":"gemmachanminnerva"},
    { "source":"avengersinfinitywar", "target":"peterdinklageeitri"},
    { "source":"phasetwo", "target":"paulruddscottlang|antman"},
    { "source":"avengersendgame", "target":"doncheadlejamesrhodeyrhodes|warmachine"},
    { "source":"phasetwo", "target":"laurahaddockmeredithquill"},
    { "source":"avengersendgame", "target":"benedictwongwong"},
    { "source":"phasetwo", "target":"michaeldouglashankpym"},
    { "source":"blackpanther", "target":"angelabassettramonda"},
    { "source":"spidermanfarfromhome", "target":"dawnmichellekingedith"},
    { "source":"avengersendgame", "target":"jacobbatalonnedleeds"},
    { "source":"blackpanther", "target":"sterlingkbrownnjobu"},
    { "source":"spidermanhomecoming", "target":"tomhollandpeterparker|spiderman"},
    { "source":"doctorstrange", "target":"michaelstuhlbargnicodemuswest"},
    { "source":"spidermanhomecoming", "target":"michaelbarbiericharles"},
    { "source":"phasetwo", "target":"emilyvancampsharoncarter"},
    { "source":"avengersendgame", "target":"vindieselgroot"},
    { "source":"phasetwo", "target":"natalieportmanjanefoster"},
    { "source":"avengersendgame", "target":"marisatomeimayparker"},
    { "source":"thorragnarok", "target":"rachelhousetopaz"},
    { "source":"guardiansofthegalaxyvol2", "target":"zoesaldañagamora"},
    { "source":"phasetwo", "target":"andyserkisulyssesklaue"},
    { "source":"phasetwo", "target":"gregghenrygrandpaquill"},
    { "source":"avengersinfinitywar", "target":"davebautistadraxthedestroyer"},
    { "source":"phasetwo", "target":"djimonhounsoukorath"},
    { "source":"spidermanhomecoming", "target":"loganmarshallgreenjacksonbrice|shocker"},
    { "source":"spidermanfarfromhome", "target":"zendayamichellemj"},
    { "source":"spidermanfarfromhome", "target":"benmendelsohntalos"},
    { "source":"captainmarvel", "target":"leepaceronantheaccuser"},
    { "source":"phasetwo", "target":"doncheadlejamesrhodeyrhodes|warmachine"},
    { "source":"phasetwo", "target":"vindieselgroot"},
    { "source":"blackpanther", "target":"forestwhitakerdenzelwhitakerzuri"},
    
    { "source":"avengersinfinitywar", "target":"paulbettanyvision"},
    { "source":"captainamericacivilwar", "target":"chrisevanssteverogers|captainamerica"},
    { "source":"avengersendgame", "target":"cobiesmuldersmariahill"},
    { "source":"avengersendgame", "target":"hayleyatwellpeggycarter"},
    { "source":"guardiansofthegalaxyvol2", "target":"mikeescamillascrote"},
    { "source":"antmanandthewasp", "target":"michaelpeñaluis"},
    
    { "source":"spidermanhomecoming", "target":"michaelchernusphineasmason|tinkerer"},
    { "source":"blackpanther", "target":"danaiguriraokoye"},
    { "source":"avengersinfinitywar", "target":"williamhurtthaddeusthunderboltross"},
    { "source":"guardiansofthegalaxyvol2", "target":"joefriaoblo"},
    { "source":"avengersendgame", "target":"letitiawrightshuri"},
    { "source":"thorragnarok", "target":"taikawaititikorg"},
    { "source":"blackpanther", "target":"zolawilliamsyama"},
    { "source":"phasetwo", "target":"idriselbaheimdall"},

    { "source":"guardiansofthegalaxyvol2", "target":"gregghenrygrandpaquill"},
    { "source":"phasetwo", "target":"chrishemsworththor"},
    { "source":"avengersendgame", "target":"bradleycooperrocket"},
    { "source":"avengersendgame", "target":"hiroyukisanadaakihiko"},
    { "source":"avengersinfinitywar", "target":"joshbrolinthanos"},
    { "source":"avengersinfinitywar", "target":"zoesaldañagamora"},
    { "source":"antmanandthewasp", "target":"daviddastmalchiankurt"},
    { "source":"avengersendgame", "target":"frankgrillobrockrumlow"},
    { "source":"captainamericacivilwar", "target":"paulbettanyvision"},
    { "source":"avengersendgame", "target":"chrisevanssteverogers|captainamerica"},
    { "source":"phasetwo", "target":"bradleycooperrocket"},
    { "source":"avengersendgame", "target":"winstondukembaku"},
    { "source":"spidermanhomecoming", "target":"hannibalburesscoachwilson"},
    { "source":"avengersendgame", "target":"renerussofrigga"},
    { "source":"captainamericacivilwar", "target":"scarlettjohanssonnatasharomanoff|blackwidow"},
    { "source":"captainamericacivilwar", "target":"johnslatteryhowardstark"},
    { "source":"guardiansofthegalaxyvol2", "target":"laurahaddockmeredithquill"},
    { "source":"spidermanfarfromhome", "target":"samuelljacksonnickfury"},
    { "source":"thorragnarok", "target":"tomhiddlestonloki"},
    { "source":"doctorstrange", "target":"benedictwongwong"},
    { "source":"avengersendgame", "target":"tomvaughanlawlorebonymaw"},
    { "source":"captainamericacivilwar", "target":"danielbrühlhelmutzemo"},
    { "source":"phasetwo", "target":"leepaceronantheaccuser"},
    { "source":"avengersendgame", "target":"rossmarquandjohannschmidt|redskull"},
    { "source":"phasetwo", "target":"renerussofrigga"},
    { "source":"avengersendgame", "target":"tomhiddlestonloki"},
    { "source":"captainmarvel", "target":"lashanalynchmariarambeau"},
    { "source":"spidermanhomecoming", "target":"garcellebeauvaisdoristoomes"},
    { "source":"blackpanther", "target":"janeshiaadamsginyardnomble"},
    { "source":"thorragnarok", "target":"jeffgoldblumgrandmaster"},
    { "source":"avengersinfinitywar", "target":"karengillannebula"},
    { "source":"captainmarvel", "target":"runetemtebronchar"},
    { "source":"guardiansofthegalaxyvol2", "target":"evanjonesretch"},
    { "source":"antmanandthewasp", "target":"waltongogginssonnyburch"},
    { "source":"spidermanhomecoming", "target":"angouriericebettybrant"},
    { "source":"guardiansofthegalaxyvol2", "target":"michelleyeohaletaogord"},
    { "source":"spidermanhomecoming", "target":"abrahamattahabraham"},
    { "source":"avengersendgame", "target":"kerrycondonfriday"},
    { "source":"phasetwo", "target":"michaelrookeryonduudonta"},
    { "source":"doctorstrange", "target":"benedictcumberbatchdormammu"},
    { "source":"avengersinfinitywar", "target":"ethandizontiny"},
    { "source":"avengersendgame", "target":"benedictcumberbatchstephenstrange"},
    
    { "source":"avengersinfinitywar", "target":"moniquegandertonproximamidnight"},
    { "source":"avengersendgame", "target":"pomklementieffmantis"},
    { "source":"avengersinfinitywar", "target":"anthonymackiesamwilson|falcon"},
    { "source":"avengersinfinitywar", "target":"isabellaamarasally"},
    { "source":"phasetwo", "target":"karengillannebula"},
    { "source":"avengersendgame", "target":"samuelljacksonnickfury"},
    { "source":"avengersinfinitywar", "target":"pomklementieffmantis"},
    { "source":"spidermanhomecoming", "target":"jonfavreauharoldhappyhogan"},
    { "source":"avengersendgame", "target":"michaeldouglashankpym"},
    { "source":"blackpanther", "target":"chadwickbosemantchalla|blackpanther"},
    { "source":"spidermanfarfromhome", "target":"tomhollandpeterparker|spiderman"},
    { "source":"avengersinfinitywar", "target":"tomhollandpeterparker|spiderman"},
    { "source":"phasetwo", "target":"johnslatteryhowardstark"},
    
    { "source":"guardiansofthegalaxyvol2", "target":"chrisprattpeterquill|starlord"},
    { "source":"captainamericacivilwar", "target":"hopedavismariastark"},
    { "source":"phasetwo", "target":"beniciodeltorotaneleertivan|thecollector"},
    { "source":"phasetwo", "target":"tadanobuasanohogun"},
    { "source":"avengersinfinitywar", "target":"bradleycooperrocket"},
    { "source":"captainamericacivilwar", "target":"chadwickbosemantchalla|blackpanther"},
    { "source":"phasetwo", "target":"tysimpkinsharleykeener"},
    { "source":"phasetwo", "target":"judygreermaggie"},
    { "source":"antmanandthewasp", "target":"laurencefishburnebillfoster"},
    { "source":"avengersendgame", "target":"karengillannebula"},
    { "source":"avengersendgame", "target":"tomhollandpeterparker|spiderman"},
    { "source":"blackpanther", "target":"sydellenoelxoliswa"},
    { "source":"spidermanhomecoming", "target":"garyweeksfoster"},
    { "source":"phasetwo", "target":"avarussolilabarton"},
    { "source":"spidermanhomecoming", "target":"jacobbatalonnedleeds"},
    { "source":"guardiansofthegalaxyvol2", "target":"sylvesterstallonestakarogord"},
    { "source":"blackpanther", "target":"michaelbjordannjadaka"},
    { "source":"guardiansofthegalaxyvol2", "target":"stephenblackehartbrahl"},
    { "source":"spidermanhomecoming", "target":"zendayamichellemj"},
    { "source":"thorragnarok", "target":"clancybrownsurtur"},
    { "source":"captainmarvel", "target":"annettebeningmarvellwendylawson"},
    { "source":"spidermanhomecoming", "target":"gwynethpaltrowvirginiapepperpotts"},
    { "source":"avengersendgame", "target":"davebautistadraxthedestroyer"},
    { "source":"avengersendgame", "target":"tessathompsonvalkyrie"},
    { "source":"avengersinfinitywar", "target":"doncheadlejamesrhodeyrhodes|warmachine"},
    { "source":"avengersinfinitywar", "target":"benedictcumberbatchstephenstrange"},
    { "source":"avengersinfinitywar", "target":"vindieselgroot"},
    { "source":"avengersendgame", "target":"chrisprattpeterquill|starlord"},
    { "source":"phasetwo", "target":"zacharylevifandral"},
    { "source":"guardiansofthegalaxyvol2", "target":"davebautistadraxthedestroyer"},
    { "source":"spidermanhomecoming", "target":"jenniferconnellykaren"},
    { "source":"avengersinfinitywar", "target":"samuelljacksonnickfury"},
    
    
    { "source":"blackpanther", "target":"andyserkisulyssesklaue"},
    { "source":"captainmarvel", "target":"judelawyonrogg"},
    { "source":"avengersinfinitywar", "target":"tiffanyespensencindy"},
    { "source":"blackpanther", "target":"sebastianstanjamesbuckybarnes|wintersoldier"},
    { "source":"guardiansofthegalaxyvol2", "target":"elizabethdebickiayesha"},
    { "source":"blackpanther", "target":"florencekasumbaayo"},
    { "source":"spidermanhomecoming", "target":"johnpenickmrhapgood"},
    { "source":"avengersendgame", "target":"michaeljamesshawcorvusglaive"},
    { "source":"phasetwo", "target":"bobbycannavalejimpaxton"},
    { "source":"spidermanfarfromhome", "target":"numanacardimitri"},
    { "source":"captainmarvel", "target":"algenisperezsotoattlass"},
    { "source":"avengersendgame", "target":"terrynotarycullobsidian"},
    { "source":"guardiansofthegalaxyvol2", "target":"vingrhamescharlie"},
    { "source":"captainmarvel", "target":"scarlettjohanssonnatasharomanoff|blackwidow"},
    { "source":"avengersinfinitywar", "target":"winstondukembaku"},
    { "source":"avengersendgame", "target":"cadewoodwardnathanielbarton"},
    { "source":"phasetwo", "target":"rossmarquandjohannschmidt|redskull"},
    { "source":"avengersendgame", "target":"maximilianohernándezjaspersitwell"},
    { "source":"phasetwo", "target":"robertredfordalexanderpierce"},
    { "source":"blackpanther", "target":"martinfreemaneverettkross"},
    { "source":"captainamericacivilwar", "target":"frankgrillobrockrumlow"},
    
    { "source":"avengersinfinitywar", "target":"scarlettjohanssonnatasharomanoff|blackwidow"},
    { "source":"captainmarvel", "target":"clarkgreggphilcoulson"},
    { "source":"phasetwo", "target":"tiptiharrisdave"},
    { "source":"doctorstrange", "target":"lindalouiseduantinaminoru"},
    { "source":"doctorstrange", "target":"chiwetelejioforkarlmordo"},
    { "source":"thorragnarok", "target":"cateblanchetthela"},
    { "source":"phasetwo", "target":"samuelljacksonnickfury"},
    { "source":"phasetwo", "target":"daviddastmalchiankurt"},
    { "source":"avengersinfinitywar", "target":"idriselbaheimdall"},
    { "source":"avengersinfinitywar", "target":"florencekasumbaayo"},
    { "source":"avengersendgame", "target":"bensakamotocooperbarton"},
    { "source":"spidermanfarfromhome", "target":"peterbillingsleywilliamginterriva"},
    { "source":"spidermanfarfromhome", "target":"jbsmoovejuliusdell"},
    { "source":"phasetwo", "target":"emmafuhrmanncassielang"},
    { "source":"avengersendgame", "target":"robertredfordalexanderpierce"},
    { "source":"thorragnarok", "target":"tessathompsonvalkyrie"},
    { "source":"guardiansofthegalaxyvol2", "target":"michaelrosenbaummartinex"},
    { "source":"guardiansofthegalaxyvol2", "target":"tommyflanagantullk"},
    { "source":"blackpanther", "target":"winstondukembaku"},
    { "source":"doctorstrange", "target":"markanthonybrightondanieldrumm"},
    { "source":"avengersendgame", "target":"chadwickbosemantchalla|blackpanther"},
    { "source":"blackpanther", "target":"danielkaluuyawkabi"},
    { "source":"avengersendgame", "target":"michellepfeifferjanetvandyne"},
    { "source":"captainmarvel", "target":"brielarsoncaroldanvers|captainmarvel"},
    { "source":"spidermanhomecoming", "target":"jorgelendeborgjrjasonionello"},
    { "source":"doctorstrange", "target":"tildaswintonancientone"},
    { "source":"captainmarvel", "target":"benmendelsohntalos"},
    { "source":"spidermanhomecoming", "target":"jjtotahseymour"},
    
    { "source":"avengersendgame", "target":"anthonymackiesamwilson|falcon"},
    { "source":"avengersendgame", "target":"brielarsoncaroldanvers|captainmarvel"},
    { "source":"thorragnarok", "target":"chrishemsworththor"},
    { "source":"captainamericacivilwar", "target":"paulruddscottlang|antman"},
    { "source":"spidermanhomecoming", "target":"tiffanyespensencindy"},
    { "source":"avengersendgame", "target":"angelabassettramonda"},
    { "source":"captainmarvel", "target":"chrisevanssteverogers|captainamerica"},
    { "source":"phasetwo", "target":"zoesaldañagamora"},
    { "source":"spidermanhomecoming", "target":"bokeemwoodbinehermanschultz|shocker"},
    { "source":"phasetwo", "target":"sethgreenhowardtheduck"},
    { "source":"doctorstrange", "target":"benedictcumberbatchstephenstrange"},
    { "source":"spidermanfarfromhome", "target":"remyhiibraddavis"},
    { "source":"phasetwo", "target":"frankgrillobrockrumlow"},
    { "source":"phasetwo", "target":"jeremyrennerclintbarton|hawkeye"},
    { "source":"phasetwo", "target":"gwynethpaltrowvirginiapepperpotts"},
    { "source":"avengersendgame", "target":"danaiguriraokoye"},
    { "source":"antmanandthewasp", "target":"randallparkjimmywoo"},
    { "source":"avengersendgame", "target":"paulruddscottlang|antman"},
    { "source":"avengersendgame", "target":"williamhurtthaddeusthunderboltross"},
    { "source":"spidermanfarfromhome", "target":"jorgelendeborgjrjasonionello"},
    { "source":"captainmarvel", "target":"annettebeningsupremeintelligence"},
    { "source":"doctorstrange", "target":"rachelmcadamschristinepalmer"},
    
    { "source":"guardiansofthegalaxyvol2", "target":"michaelrookeryonduudonta"},
    { "source":"avengersinfinitywar", "target":"chrisprattpeterquill|starlord"},
    { "source":"avengersinfinitywar", "target":"danaiguriraokoye"},
    { "source":"blackpanther", "target":"lupitanyongonakia"},
    { "source":"avengersinfinitywar", "target":"beniciodeltorotaneleertivan|thecollector"},
    { "source":"spidermanhomecoming", "target":"kennethchoiprincipalmorita"},
    { "source":"phasetwo", "target":"robertdowneyjrtonystark|ironman"},
    { "source":"phasetwo", "target":"elizabetholsenwandamaximoff"},
    { "source":"guardiansofthegalaxyvol2", "target":"terencerosemorenarblik"},
    { "source":"spidermanhomecoming", "target":"tynedalyannemariehoag"},
    { "source":"captainamericacivilwar", "target":"jeremyrennerclintbarton|hawkeye"},
    
    { "source":"spidermanhomecoming", "target":"martinstarrrogerharrington"},
    { "source":"antmanandthewasp", "target":"michaeldouglashankpym"},
    { "source":"captainamericacivilwar", "target":"elizabetholsenwandamaximoff"},
    { "source":"avengersendgame", "target":"evangelinelillyhopevandyne|wasp"},
    { "source":"spidermanhomecoming", "target":"lauraharrierliz"},
    { "source":"antmanandthewasp", "target":"michellepfeifferjanetvandyne"},
    { "source":"avengersinfinitywar", "target":"sebastianstanjamesbuckybarnes|wintersoldier"},
    { "source":"blackpanther", "target":"johnkaniatandwakanitchaka"},
    { "source":"captainmarvel", "target":"doncheadlejamesrhodeyrhodes|warmachine"},
    { "source":"phasetwo", "target":"clarkgreggphilcoulson"},
    { "source":"avengersendgame", "target":"seangunnkraglinobfonteri"},
    { "source":"antmanandthewasp", "target":"bobbycannavalejimpaxton"},
    { "source":"avengersendgame", "target":"alexandrarachaelrabemorganstark"},
    { "source":"captainamericacivilwar", "target":"kerrycondonfriday"},
    { "source":"avengersendgame", "target":"sebastianstanjamesbuckybarnes|wintersoldier"},
    { "source":"avengersendgame", "target":"taikawaititikorg"},
    { "source":"captainamericacivilwar", "target":"williamhurtthaddeusthunderboltross"},
    { "source":"avengersendgame", "target":"zoesaldañagamora"},
    { "source":"avengersendgame", "target":"natalieportmanjanefoster"},
    { "source":"avengersinfinitywar", "target":"jacobbatalonnedleeds"},
    { "source":"spidermanhomecoming", "target":"isabellaamarasally"},
    { "source":"thorragnarok", "target":"idriselbaheimdall"},
    { "source":"phasetwo", "target":"raystevensonvolstagg"},
    { "source":"avengersinfinitywar", "target":"janeshiaadamsginyardnomble"},
    { "source":"antmanandthewasp", "target":"tiptiharrisdave"},
    { "source":"avengersendgame", "target":"tysimpkinsharleykeener"},
    { "source":"captainamericacivilwar", "target":"alfrewoodardmiriamsharpe"},
    { "source":"avengersinfinitywar", "target":"cobiesmuldersmariahill"},
    { "source":"spidermanhomecoming", "target":"robertdowneyjrtonystark|ironman"},
    { "source":"avengersendgame", "target":"scarlettjohanssonnatasharomanoff|blackwidow"},
    { "source":"phasetwo", "target":"bensakamotocooperbarton"},
    { "source":"antmanandthewasp", "target":"abbyryderfortsoncassielang"},
    { "source":"phasetwo", "target":"tomhiddlestonloki"},
    { "source":"thorragnarok", "target":"anthonyhopkinsodin"},
    { "source":"phasetwo", "target":"seangunnkraglinobfonteri"},
    
    { "source":"avengersinfinitywar", "target":"markruffalobrucebanner|hulk"},
    { "source":"avengersinfinitywar", "target":"elizabetholsenwandamaximoff"},
    { "source":"captainamericacivilwar", "target":"doncheadlejamesrhodeyrhodes|warmachine"},
    { "source":"avengersinfinitywar", "target":"benedictwongwong"},
    
    { "source":"antmanandthewasp", "target":"evangelinelillyhopevandyne|wasp"},
    { "source":"avengersendgame", "target":"lindacardellinilaurabarton"},
    { "source":"avengersinfinitywar", "target":"chadwickbosemantchalla|blackpanther"},
    { "source":"doctorstrange", "target":"madsmikkelsenkaecilius"},
    { "source":"spidermanfarfromhome", "target":"martinstarrrogerharrington"},
    { "source":"thorragnarok", "target":"markruffalobrucebanner|hulk"},
    
    { "source":"spidermanhomecoming", "target":"selenisleyvamswarren"},
    { "source":"captainamericacivilwar", "target":"tomhollandpeterparker|spiderman"},
    { "source":"phasetwo", "target":"martinstarrrogerharrington"},
    
    { "source":"spidermanfarfromhome", "target":"jacobbatalonnedleeds"},
    { "source":"avengersendgame", "target":"jonfavreauharoldhappyhogan"},
    { "source":"avengersinfinitywar", "target":"terrynotarycullobsidian"},
    { "source":"spidermanhomecoming", "target":"michaelmandomacgargan"},
    { "source":"avengersinfinitywar", "target":"carriecoonproximamidnight"},
    { "source":"captainamericacivilwar", "target":"florencekasumbaayo"},
    { "source":"antmanandthewasp", "target":"hannahjohnkamenavastarr|ghost"},
    { "source":"guardiansofthegalaxyvol2", "target":"seangunnkraglinobfonteri"},
    { "source":"avengersendgame", "target":"chrishemsworththor"},
    { "source":"captainmarvel", "target":"markruffalobrucebanner|hulk"},
    { "source":"avengersinfinitywar", "target":"tomhiddlestonloki"},
    { "source":"spidermanfarfromhome", "target":"jksimmonsjjonahjameson"},
    { "source":"avengersinfinitywar", "target":"chrishemsworththor"},
    { "source":"spidermanfarfromhome", "target":"sharonblynnsoren"},
    { "source":"thorragnarok", "target":"raystevensonvolstagg"},
    { "source":"phasetwo", "target":"paulbettanyvision"},
    { "source":"avengersinfinitywar", "target":"gwynethpaltrowvirginiapepperpotts"},
    { "source":"guardiansofthegalaxyvol2", "target":"bradleycooperrocket"},
    { "source":"phasetwo", "target":"chrisprattpeterquill|starlord"},
    { "source":"phasetwo", "target":"joshbrolinthanos"},
    
    { "source":"blackpanther", "target":"letitiawrightshuri"},
    { "source":"phasetwo", "target":"chrisevanssteverogers|captainamerica"},
    { "source":"avengersendgame", "target":"robertdowneyjrtonystark|ironman"},
    { "source":"phasetwo", "target":"williamhurtthaddeusthunderboltross"},
    { "source":"captainmarvel", "target":"samuelljacksonnickfury"},
    
    { "source":"avengersinfinitywar", "target":"zolawilliamsyama"},
    { "source":"guardiansofthegalaxyvol2", "target":"vindieselgroot"},
    { "source":"phasetwo", "target":"anthonymackiesamwilson|falcon"},
    { "source":"avengersinfinitywar", "target":"letitiawrightshuri"},
    { "source":"phasetwo", "target":"davebautistadraxthedestroyer"},
    { "source":"phasetwo", "target":"jonfavreauharoldhappyhogan"},
    { "source":"spidermanhomecoming", "target":"hemkymaderamrdelmar"},
    { "source":"avengersendgame", "target":"jeremyrennerclintbarton|hawkeye"},
    { "source":"captainamericacivilwar", "target":"marisatomeimayparker"},
    { "source":"blackpanther", "target":"nabiyahbelinda"},
    { "source":"antmanandthewasp", "target":"divianladwauzman"},
    { "source":"avengersendgame", "target":"joshbrolinthanos"},
    { "source":"avengersendgame", "target":"emmafuhrmanncassielang"},
    
    { "source":"captainamericacivilwar", "target":"emilyvancampsharoncarter"},
    { "source":"phasetwo", "target":"callanmulveyjackrollins"},
    { "source":"thorragnarok", "target":"tadanobuasanohogun"},
    { "source":"avengersendgame", "target":"elizabetholsenwandamaximoff"},
    { "source":"spidermanhomecoming", "target":"tonyrevolorieugeneflashthompson"},
    { "source":"spidermanfarfromhome", "target":"jakegyllenhaalquentinbeck|mysterio"},
    { "source":"avengersinfinitywar", "target":"rossmarquandjohannschmidt|redskull"},
    
    { "source":"thorragnarok", "target":"zacharylevifandral"},
    { "source":"phasetwo", "target":"sebastianstanjamesbuckybarnes|wintersoldier"},
    { "source":"spidermanhomecoming", "target":"chrisevanssteverogers|captainamerica"},
    { "source":"phasetwo", "target":"kerrycondonfriday"},
    { "source":"phasetwo", "target":"cobiesmuldersmariahill"},
    
    { "source":"guardiansofthegalaxyvol2", "target":"karengillannebula"}
  
      ]}